### PR TITLE
fix: Scroll MapView to first campus on load

### PR DESCRIPTION
**Pull request by vinnyjth**
### What does this PR do, or why is it needed?

Scrolls the map view to the closest campus on load. 

### How do I test this PR?

Best place to test is the new `MapViewConnected` story,

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
@vinnyjth this one ready?

**Comment by redreceipt** [comment]
trying to test, set my location to greenville and reloaded, nothing changed
Screen Shot 2020-09-29 at 10 51 18 PM

**Comment by redreceipt** [comment]
also, dallas isn't 101 mi from cali or greenville so I'm not sure the test is valid

**Comment by vinnyjth** [comment]
@redreceipt I hand wrote that data 😬

Your screen looks right to me, that's the "zoomed in" state. The data is all mocked (including what campus is actually closest). The test is that it zooms in to include the Dallas location and your current location on mount, rather than the current behavior, which zooms out to the whole US.

**Comment by redreceipt** [comment]
Oh 😄

**Review by redreceipt — APPROVED** [review]

**Pull request merged**
