### PR TITLE
chore: Community Tab Empty State

### PR DESCRIPTION
**Pull request by calebpanza**
## ✏️ Description
If a user is not a part of any communities, we want to show them a unique screen that invites them to participate in a Community.

In order to do this, we check to see if the user is in any communities and if they aren't we render a unique component instead of the Stream Activity Feed. When a user joins/leaves a Community, this screen adjusts appropriate to the number of Communities the user is in.

## 🔬 To Test
1. Open up the Communities Tab
2. Remove yourself from any communities you are a member of
3. Check to see the Communities tab now shows the custom empty state
4. Join a community
5. Check to see that the communities tab now updates to show communtiies

## 📸 Screenshots

https://user-images.githubusercontent.com/45076058/198084215-302bb907-128b-4be4-a24b-f7151ff20314.mp4

## ⚠️ To-do Before Merge
- [x] Ensure that #2734 and #2721 are merged into `master`

## 📝 Checklist
- [x] I have performed a self-review of my code
- [x] I have tested my code works in the project (nothing breaks)
- [x] I have commented my code in hard-to-understand areas
- [x] New and existing tests and linting pass locally with my changes
- [x] I have made corresponding changes to the documentation (new envs?)

### CODE REVIEW

**Comment by conrad-vanl** [comment]
So @calebpanza I hate to break it to you, but I'm not sure I'm loving the illustrations. 

WDYT about just using the Phosphor community icon?

image

I favor simple iconography for stuff like this. For perhaps a few reasons:

1. White-label perspective of Apollos. Ultimately Apollos is white-label and we have to be really conscious with visual design decisions so as to not conflict with the visual execution of any of our clients and to limit potential areas of push back
2. The current design language of Apollos is focused on simplistic, native looking iconography. This charcoal sketch illustration style is new and does not exist currently.
   - For this reason alone, I think we should probably remove this style illustration on the other error state screen you've mocked up, and replace it with a duotone phosphor icon.

With that said, I'm actually interested in exploring some visual execution stuff like this...I'm trying to get time with Tyler to explore this some more and go deep on creating a visual style that would be more specific to Apollos and still scale well to our clients.

Thoughts? I value your input on this, and I actually would prefer you to continue exploring unique concepts in your PRs

**Comment by calebpanza** [comment]
@conrad-vanl I understand completely! Not disappointed at all cause I was low-key expecting it. Lol.

I actually reached out to the design channel on slack because I think these sketches represent an interesting concept, but are not at the state of polish that I would consider them a hill to die on. Lol

> White-label perspective of Apollos.
With the right art style, I actually think that illustrations play to this more than iconography does

> With that said, I'm actually interested in exploring some visual execution stuff like this
I'm totally fine reverting these to the duotone icon approach and opening up some time to discussing a more "Apollos-y" approach to this. I'm sure that @jordanwade could benefit from this as well on the TV side. If appropriate, I'd love if we were in on those discussions cause there are a couple of screens (Auth, Communities and Daily Habit off the top of my head) that would benefit

> I actually would prefer you to continue exploring unique concepts in your PRs
I greatly appreciate that and will continue to try things out! When applicable, I'll try to sketch them in Figma first so conversations can be a bit quicker, too

**Comment by calebpanza** [comment]
@conrad-vanl all set on this one. I'll get the 404 updated in another PR. I need to make some changes to the routing anyways.

CleanShot 2022-10-26 at 14 01 09

**Comment by calebpanza** [comment]
> wdyt about increasing the horizontal padding of this element to 32px

Ah! Good catch. That's my bad. Not intentionally different from Figma. I must have misread when moving too quickly

> how do you have the vertical spacing

Vertical spacing is just centering the elements in dead center on the screen

> and icon size setup

I felt like the icon wasn't substantial enough and too much negative space made it feel like something was missing. Since we opted out of an image, I played around with it in [Figma](https://www.figma.com/file/YHJLj8pdFxWG9npF2YmB3r/UI-Kit-2.0?node-id=4103%3A58629). I wanna make sure that whatever is represented on that screen really captures a user's attention and draws them in and found a larger icon to add a bit of "oomph" to it. I can change it if you'd like! It was more of a "gut decision" than anything.

**Comment by conrad-vanl** [comment]
Re: Icon Sizing

Yeah, I'd like to standardize the icon sizes we support. 

24 and 32 are the two most common icon sizes we use.
I had 48 in Figma as it's 2x the size of 24.

I could see 64 as another common size.

You have 85. 85 isn't divisible by our base unit. It's also much much larger I think then any other icon size we have currently. It _feels_ big to me right now, but I realize that's highly subjective.

**Comment by calebpanza** [comment]
Yeah that's a fair point. I wasn't really thinking in terms of "standards". I'll go ahead and revert it to the 48px

**Comment by jordanwade** [comment]
@calebpanza I was going to comment something similar to Conrad around the illustration. I was wondering if Apollos has an illustration motif. I do personally like the idea of adding illustration type elements to areas like this, but I see where Conrad is coming from and his leaning towards keeping things simple. 

I hope Tyler and or other designers get the time to really craft more illustrative type things for our products. I really enjoy apps that execute that stuff well.

**Comment by calebpanza** [comment]
@jordanwade appreciate that! And I'm with you guys. That illustration was actually a DALL-E image that I was playing around with/trying to sneak in, but totally understand it to not be production-ready!

**Review by vinnyjth — CHANGES_REQUESTED** [review]
I think your cool dall-e images are still in the codebase :)

**Comment by calebpanza** [comment]
Removed!

**Pull request merged**
