### PR TITLE
feat: removed scripture component and add htmlFeature

### PR DESCRIPTION
**Pull request by camrun91**
This puts in place a very simple HTML Feature. it works with the scripture detection from earlier this week. 

Screen Shot 2022-06-03 at 12 30 48 PM

### CODE REVIEW

**Comment by camrun91** [comment]
@conrad-vanl @redreceipt I am completely open to any styling changes you have on how that renders. Right now it renders the straight HTML in a padded view.

**Comment by redreceipt** [comment]
I have no opinion on design. But could you give me a little test coverage :) a snap should be fine

**Review by redreceipt — APPROVED** [review]

**Comment by camrun91** [comment]
hmmm ok, the test is passing locally but failing here...

**Comment by calebpanza** [comment]
@camrun91 personally, I like that it just renders right on the screen. I wouldn't change a thing on it

**Pull request merged**
