### PR TITLE
Reorganizes Sharing in API

### PR DESCRIPTION
**Pull request by redreceipt**
### What does this PR do, or why is it needed?

While this adds a bit of complexity, it adds a lot of a clarity too. And makes extending bits and pieces of sharing for churches much more granular.

- Renames sharing data structures to match convention
- Defined sharing resolvers more explicitly to make extending by churches easier

### What design trade-offs/decisions were made?

Deprecated the old names

### How do I test this PR?

```
{
  userFeed {
    edges {
      node {
        ... on WeekendContentItem {
          id
          features {
            ... on ScriptureFeature {

              sharing {
                title
                message
              }
            }
          }
          siblingContentItemsConnection {
            edges {
              node {
                id
                sharing {
                  title
                  message
                  url
                }
              }
            }
          }
        }
      }
    }
  }
}
```

### What automated tests did you write?

None

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes [#1060]
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
@redreceipt I can tentatively approve this, but need to do some testing first. Normally you can't change the name of GQL types without introducing breaking changes, but because you're not changing any of the field names (and just the names of the types themselves) we might be okay. 

I wholeheartedly approve of the resolver changes based on my glance over them, nice work.

**Comment by redreceipt** [comment]
I left the old ones in there and just deprecated them

**Comment by vinnyjth** [comment]
@redreceipt Ultimately that won't help us, because the types of existing fields changes. Check the backwards compatibility errors coming from Travis.

**Comment by redreceipt** [comment]
Oh shoot, yea I figured that would be a breaking change but wouldn't affect anything since no one calls those field types directly. If there's some way around it just let me know. I guess we could deprecate `sharing` and call the field something else but I think that's the best name for the field. I tested our client with it and still seems to work fine.

**Comment by richarddubay** [comment]
@vinnyjth Any idea when this broke? I'm mostly just curious. We had/have a custom resolver for the URL part of sharing (I _think_ because of the way our links are structured, if I remember right), but it appears that something happened on the core end that made it so that our custom resolver wasn't doing anything? @redreceipt Feel free to correct me if that's wrong. That's concerning. So I'm just trying to track down a why/when so I can understand.

**Comment by vinnyjth** [comment]
@richarddubay I'm not sure I understand the context here. Looks like from here that you should still be able to override the share URL, but how that's accomplished might have changed? 

@redreceipt Do you think you could implement the resolver reorganizing that's in this PR separate from the schema changes? If you do that, I can merge this PR without worry, and we can talk about the best way to change the naming of the types long term.

**Comment by redreceipt** [comment]
Instead of trying to decouple it here and put it back later, I'll just override the `sharing` field in our API temporarily.

I think we still figure out how to rename stuff here. I'm hoping there may be a few interested candidates after the Rock Conference so I want to keep pushing to make things clear and developer-friendly on core.

**Comment by richarddubay** [comment]
@vinnyjth Yeah, I just know sharing and the URL used to work and we have an override. Now it doesn’t seem to work. Which just tells me that something changed, I’m guessing on the core end, that doesn’t allow that override we have to work anymore. I’m just trying to figure out where that happened.

**Comment by redreceipt** [comment]
> @vinnyjth Yeah, I just know sharing and the URL used to work and we have an override. Now it doesn’t seem to work. Which just tells me that something changed, I’m guessing on the core end, that doesn’t allow that override we have to work anymore. I’m just trying to figure out where that happened.

see my comment above. I broke it two months ago.

**Comment by conrad-vanl** [comment]
@vinnyjth @redreceipt what's the latest thinking of this? There's parts of this I like... Looks like latest request from @vinnyjth:

> Do you think you could implement the resolver reorganizing that's in this PR separate from the schema changes? If you do that, I can merge this PR without worry, and we can talk about the best way to change the naming of the types long term.

But it sounds like @redreceipt's response was that you'll just do this separately in NewSpring.

Lets close this if it's no longer interesting / planned to work on.

**Comment by redreceipt** [comment]
@conrad-vanl I still think there's merit in reorganizing without changing names. Let me throw that together and see what you think

**Comment by redreceipt** [comment]
Although I am a little confused about why the naming is a problem if the names are better and the old names are properly deprecated?

**Comment by redreceipt** [comment]
Although I am a little confused about why the naming is a problem if the names are better and the old names are properly deprecated? In order to do this right, I have to break up the SharableFeature schema anyway because the message has to be resolved differently for scripture vs text features.

**Pull request closed without merging**
