### PR TITLE
chore: change fetch policy so that prayers show up

### PR DESCRIPTION
**Pull request by nlewis84**
This PR changes the fetch policy on prayers to network-only so that prayer requests show up more quickly in app.

### CODE REVIEW

**Comment by nlewis84** [comment]
@redreceipt Shoot me down if this is a bad idea.

**Comment by redreceipt** [comment]
Not sure the performance hit is worth it. With cache and network, it should be correct on the following pull.

**Comment by redreceipt** [comment]
yea we should figure out why it's not there on the next pull

**Comment by nlewis84** [comment]
Pulled down the latest template files to grab the changes to client.js that @calebpanza was working on. Same trouble. I'll keep at it.

**Pull request closed without merging**
