### PR TITLE
fix: Error handling for initialPrompt and addPrompt resolver

### PR DESCRIPTION
**Pull request by tomthornton**

### CODE REVIEW

**Review by redreceipt — COMMENTED** [review]
I would rather find out what's going wrong and fix it for real than just a generic try catch

**Comment by tomthornton** [comment]
What's going wrong is that the shovel used to provide defaults for addPrompt and initialPrompt but I removed them. Those defaults caused them to not be null.

This could just as easily be a shovel PR, we'd just be going back and adding deprecated fields.

**Comment by redreceipt** [comment]
So why don't we just set a default at the resolver instead of an error handler?

**Comment by tomthornton** [comment]
Because I still don't know what `JSON.parse(id` does. To me, it looks like we can remove it and set defaults. I did it like this to cover all bases.

**Comment by redreceipt** [comment]
Do it. We'll fix it later if it breaks a "content from Rock" church.

**Comment by tomthornton** [comment]
@redreceipt done

**Comment by redreceipt** [comment]
@tomthornton would you add this to the cluster too

**Comment by tomthornton** [comment]
https://github.com/ApollosProject/apollos-cluster/pull/38

**Pull request merged**
