### PR TITLE
feat: Tag filter UI

### PR DESCRIPTION
**Pull request by tomthornton**
https://user-images.githubusercontent.com/40962668/141498462-ffe89e4b-1179-4427-a399-b446c982ba32.mp4

### CODE REVIEW

**Comment by redreceipt** [comment]
Can I test this on the core template app?

**Comment by tomthornton** [comment]
@redreceipt yep. I was trying to find the screen recording I did the other day, I'll try and find it or record another.

**Comment by redreceipt** [comment]
I can test easily if there's an example on the core template

**Comment by tomthornton** [comment]
@redreceipt just added a branch to templates you can test

`BRANCH=tags-test-ui yarn app`

you'll also need to run the core rock tags backfill in the shovel to pick up the correct tags

**Comment by redreceipt** [comment]
pointed it to the production server, the tags should already be in the database right?

**Comment by tomthornton** [comment]
@redreceipt backfill needs to be run. I can do that.

**Comment by redreceipt** [comment]
running this code on the master branch in templates seems to break things

Screen Shot 2021-11-12 at 11 51 51 AM

**Comment by nlewis84** [comment]
FWIW, this PR is not urgent for their soft launch on Monday.

**Comment by tomthornton** [comment]
@redreceipt github's not letting me run `yarn app` has something to do with ssh. Not sure why this wouldn't work on master templates.

**Comment by redreceipt** [comment]
this is why. the API code hasn't been released to production yet

Screen Shot 2021-11-12 at 12 14 25 PM

**Review by redreceipt — APPROVED** [review]

**Comment by redreceipt** [comment]
alright @tomthornton fix the linter error and this is good to go

**Comment by redreceipt** [comment]
i got it

**Pull request merged**
