### PR TITLE
feat: add new tab feed query

### PR DESCRIPTION
**Pull request by redreceipt**
Gives us a simple way to create more queries for more tabs without polluting the schema

test using the `tab-component` branch on templates

Screen Shot 2021-05-12 at 9 35 41 AM

### CODE REVIEW

**Comment by vinnyjth** [comment]
I'm good with this! what do you think @conrad-vanl? I know we bounced back and forth a while when initially trying to design this schema.

**Comment by redreceipt** [comment]
Same thing is hard coded, just in cleaner way. And makes the client much cleaner as well.

**Comment by conrad-vanl** [comment]
It's still not my favorite, but I'm good with it. I'm going to have more commentary on the -templates side.

Essentially, I wouldn't render the "header" within the `Tab` component, I'd do that within the react-navigation config. On the RV app, all of the tab headers (both the home page header and the large title headers on like the Read tab) should be using the native react-navigation header component. 

Also, generally we render "Tabs" inside of a react-navigation Native Stack component because some navigation transitions happen "within the tab" (keeps the tab bar fixed to bottom of screen) and some navigation transitions occur over the tab (such as opening a NodeSingle). Might want to think through that some too.

**Comment by redreceipt** [comment]
love it. yea drop some comments over there if there's anything else and I'll get it cleaned up. now someone gimme a green check!

**Review by conrad-vanl — APPROVED** [review]

**Comment by conrad-vanl** [comment]
> yea drop some comments over there
I didn't see an opened PR yet?

**Pull request merged**
