### PR TITLE
adds feed titles to action list links

### PR DESCRIPTION
**Pull request by redreceipt**
## ✏️ Description

Adds proper titles to action lists that link to feature feeds

## 🔬 To Test
1. pull up Fellowship Greenville and click on "Give Now"
2.

## 📸 Screenshots

Screenshot 2023-02-18 at 10 00 25 AM

## ⚠️ To-do Before Merge

n/a

## 📝 Checklist

- [ ] I have performed a self-review of my code
- [ ] I have tested my code works in the project (nothing breaks)
- [ ] I have commented my code in hard-to-understand areas
- [ ] New and existing tests and linting pass locally with my changes
- [ ] I have made corresponding changes to the documentation (new envs?)
- [ ] For PR's with design updates/changes, I have consulted with the product designer and made all necessary adjustments in Figma

### CODE REVIEW

**Review by conrad-vanl — APPROVED** [review]

**Comment by vinnyjth** [comment]
What renders for feeds without a title?

**Comment by conrad-vanl** [comment]
Isn't it no different then what we have now? I thought `title` was an optional prop

**Comment by redreceipt** [comment]
this puts the item title as the feed title for OPEN_FEED actions. it's our only option and technically the same thing the other approach was doing. just at the right time.

**Comment by redreceipt** [comment]
@conrad-vanl @vinnyjth this has been confusing me too. but essentially the item will always have a title (the words that show up in the action list). I'm sure that won't answer your questions so what still doesn't make sense?

**Comment by vinnyjth** [comment]
Yah looks fine to me, just wanted to make sure that because we’re now passing ‘null’ in most cases instead of undefined we don’t have a bunch of headers with “null” as a title On Feb 18, 2023, at 10:06 AM, Michael Neeley ***@***.***> wrote:﻿
this puts the item title as the feed title for OPEN_FEED actions. it's our only option and technically the same thing the other approach was doing. just at the right time.

**Comment by redreceipt** [comment]
> Yah looks fine to me, just wanted to make sure that because we’re now passing ‘null’ in most cases instead of undefined we don’t have a bunch of headers with “null” as a title On Feb 18, 2023, at 10:06 AM, Michael Neeley ***@***.***> wrote:﻿ this puts the item title as the feed title for OPEN_FEED actions. it's our only option and technically the same thing the other approach was doing. just at the right time. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because your review was requested.Message ID: ***@***.***>

think of it like this isn't using the feed title, it's using the action list item title (they are the same. it will never be null)

**Comment by redreceipt** [comment]
it will make more sense when I revert the unnecessary server PR

**Comment by vinnyjth** [comment]
Actually, should this be 'subtitle || title'? 

I would need to check the DB but I believe many features use the subtitle field in a manner that resembles a title.

@conrad-vanl can probs speak to the best case scenario here

**Comment by redreceipt** [comment]
> Actually, should this be 'subtitle || title'?
> 
> I would need to check the DB but I believe many features use the subtitle field in a manner that resembles a title.
> 
> @conrad-vanl can probs speak to the best case scenario here

we're talking about two separate things. pretend I never did that server PR. this is a different approach entirely.

**Comment by vinnyjth** [comment]
Yah I think I'm caught up. We're relying on data on the action list, which can have 'title', 'subtitle', or both right?

**Comment by redreceipt** [comment]
> Yah I think I'm caught up. We're relying on data on the action list, which can have 'title', 'subtitle', or both right?

Oh, that I'm not sure. but subtitles are typically longer and more of a description right? I think title is the right move because this will only be a thing if the action item opens a feed. I can't think of a title that would be inappropriate for the nav title

**Comment by vinnyjth** [comment]
Looks like defaulting to `title` will handle 100% of current cases well. 

`select data->>'title' as title, data->>'subtitle' as subtitle, church_slug from feature where type = 'ActionList' and data::text like '%OPEN_FEED%'`
```
[
	{
		"title": "Events",
		"subtitle": "Upcoming",
		"church_slug": "eastview"
	},
	{
		"title": "Latest",
		"subtitle": "At your campus",
		"church_slug": "bayside"
	},
	{
		"title": "Ministry",
		"subtitle": "Explore by",
		"church_slug": "city_rise"
	},
	{
		"title": "Events",
		"subtitle": "For you",
		"church_slug": "bayside"
	},
	{
		"title": null,
		"subtitle": null,
		"church_slug": "fellowship_greenville"
	},
	{
		"title": "Stories & Articles",
		"subtitle": "Recommended",
		"church_slug": "fellowship_greenville"
	},
	{
		"title": "Upcoming Events",
		"subtitle": "At your campus",
		"church_slug": "willow_creek"
	},
	{
		"title": "Topic",
		"subtitle": "Explore by",
		"church_slug": "city_rise"
	},
	{
		"title": "EVENTS",
		"subtitle": "Upcoming",
		"church_slug": "oakcliff"
	},
	{
		"title": "Upcoming Events",
		"subtitle": null,
		"church_slug": "city_first"
	},
	{
		"title": "Recommended",
		"subtitle": "For You",
		"church_slug": "fairhaven"
	},
	{
		"title": "Events",
		"subtitle": "Upcoming",
		"church_slug": "fellowship_greenville"
	}
]
```

That changes a bit when we expand to CardLists :) 

```
[
	{
		"title": null,
		"subtitle": "Sermons",
		"church_slug": "lcbc",
		"type": "HorizontalCardList"
	},
	{
		"title": null,
		"subtitle": "Mercy and Grace",
		"church_slug": "crossings_community_church",
		"type": "VerticalCardList"
	},
	{
		"title": null,
		"subtitle": "Bible Reading",
		"church_slug": "lcbc",
		"type": "HorizontalCardList"
	},
	{
		"title": "Next Steps",
		"subtitle": "For You",
		"church_slug": "woodmen",
		"type": "HeroList"
	},
	{
		"title": "The Latest",
		"subtitle": null,
		"church_slug": "crossroads_tv",
		"type": "HorizontalCardList"
	},
	{
		"title": null,
		"subtitle": "Community",
		"church_slug": "woodmen",
		"type": "HorizontalCardList"
	},
	{
		"title": null,
		"subtitle": "Stories",
		"church_slug": "woodmen",
		"type": "HorizontalCardList"
	},
	{
		"title": null,
		"subtitle": "Serving",
		"church_slug": "woodmen",
		"type": "HorizontalCardList"
	},
	{
		"title": null,
		"subtitle": "Kids",
		"church_slug": "woodmen",
		"type": "HorizontalCardList"
	},
	{
		"title": null,
		"subtitle": "Ark Valley Campus",
		"church_slug": "woodmen",
		"type": "HorizontalCardList"
	},
	{
		"title": null,
		"subtitle": "Woodmen Heights Campus",
		"church_slug": "woodmen",
		"type": "HorizontalCardList"
	},
	{
		"title": null,
		"subtitle": "Southwest Campus",
		"church_slug": "woodmen",
		"type": "HorizontalCardList"
	},
	{
		"title": null,
		"subtitle": "Giving Resources",
		"church_slug": "eleven22",
		"type": "HorizontalCardList"
	},
	{
		"title": "Discussion Guides",
		"subtitle": null,
		"church_slug": "willow_creek",
		"type": "HeroList"
	},
	{
		"title": "Devotionals",
		"subtitle": null,
		"church_slug": "willow_creek",
		"type": "HeroList"
	},
	{
		"title": "Devotional Series",
		"subtitle": null,
		"church_slug": "willow_creek",
		"type": "HorizontalCardList"
	}
]
```

**Pull request merged**
