### PR TITLE
chore: Update onboarding

### PR DESCRIPTION
**Pull request by nlewis84**
Adds a couple of slides back to onboarding.

### CODE REVIEW

**Comment by vinnyjth** [comment]
@conrad-vanl thoughts here?

**Comment by nlewis84** [comment]
Notes: Have these pages check for data and skip if it exists.

**Review by vinnyjth — APPROVED** [review]

**Review by redreceipt — APPROVED** [review]

**Comment by vinnyjth** [comment]
merged this too soon! we can get the data checking in another pr

**Comment by nlewis84** [comment]
I've actually got a new PR open now locally. Trying to figure out how to call the `onPressPrimary` function when the slide loads if that data exists.

**Pull request merged**
