### PR TITLE
feat: get comment feature from parents

### PR DESCRIPTION
**Pull request by vinnyjth**
Looks at the parent content item to determine if comments should be enabled, as well as the item itself 

Code copied over from Newspring, which will be able to eliminate custom code after this is merged.

### CODE REVIEW

**Comment by redreceipt** [comment]
Would it be better to just enable this for all `DevotionalContentItem` types?

**Comment by vinnyjth** [comment]
@redreceipt 🤷  I don't think so - It wouldn't be accurate for Newspring and we are also moving away from type based features.

**Comment by redreceipt** [comment]
That's fair, I just hate adding more hardcoded attribute value names than are necessary. For any new app to use this feature, we have to go look up what the attribute value is called. It doesn't work out of the box. I know it's the case with all the features but I really wish there was a better way to enable these features by default.

**Review by redreceipt — APPROVED** [review]

**Comment by vinnyjth** [comment]
> For any new app to use this feature, we have to go look up what the attribute value is called. It doesn't work out of the box . . . I really wish there was a better way to enable these features by default.

amen. amen. amen.

**Comment by vinnyjth** [comment]
> > For any new app to use this feature, we have to go look up what the attribute value is called. It doesn't work out of the box . . . I really wish there was a better way to enable these features by default.
> 
> amen. amen. amen.

If we had more time, maybe that could be a feature of the rock plugin? Essentially adding an easy way to toggle feature support in the Rock CMS

**Pull request merged**
