### PR TITLE
Add ui connected tests

### PR DESCRIPTION
**Pull request by jordanwade**
### What does this PR do, or why is it needed?
Adds tests to most of the `ui-connected` components.

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by conrad-vanl** [comment]
Assigning to @burkeshartsis

**Comment by conrad-vanl** [comment]
Anyone have ideas on why codecov is saying the test coverage is unchanged with this PR?

**Comment by burkeshartsis** [comment]
@conrad-vanl you know I couldn't really tell you. Only weird thing I see here is that codecov is confused because even though the commit hash (9d0c8aa) codecov seems to have a different set of changes 🤷‍♂️

image

**Comment by conrad-vanl** [comment]
@burkeshartsis does this PR still have relevance?

**Comment by burkeshartsis** [comment]
Yeah I would love to look over these still and merge them in. Test coverage over our `ui-connected` is pretty poor and I don't want to throw away @jordanwade work. I'll look at this on Thursday or Friday!

**Comment by jordanwade** [comment]
Also note, I wonder if the way I'm getting rid of the Fragment error in the tests is causes an issue with codecov, if that is still a problem. This stuff: https://github.com/ApollosProject/apollos-apps/pull/1337/files#diff-511c4e8448b461f12ca64f23365ee695R18-R21

**Comment by burkeshartsis** [comment]
😢

**Pull request closed without merging**
