### PR TITLE
working CI beta and production lanes

### PR DESCRIPTION
**Pull request by redreceipt**
## ✏️ Description

This get beta and production lanes working for everything except androidtv (untested). It also fixes Android version numbers from always being 1.0.0.

## 🔬 To Test
1. locally deploy an internal build and then promote to beta, then to production
2.

## 📸 Screenshots

Screenshot 2023-01-11 at 4 41 02 PM

## 📝 Checklist

- [x] I have performed a self-review of my code
- [x] I have tested my code works in the project (nothing breaks)
- [x] I have commented my code in hard-to-understand areas
- [x] New and existing tests and linting pass locally with my changes
- [x] I have made corresponding changes to the documentation (new envs?)
- [x] For PR's with design updates/changes, I have consulted with the product designer and made all necessary adjustments in Figma

### CODE REVIEW

**Comment by calebpanza** [comment]
Order of operations needs to _always_ start with submitting a build to `internal` first?

**Comment by redreceipt** [comment]
Beta and production lanes will pull the latest internal build whenever used.

**Comment by redreceipt** [comment]
@calebpanza I deployed Android LCBC with it just now and did Grace beta and prod yesterday with it

**Comment by calebpanza** [comment]
Sweet! That sounds good to me. I'll makes sure to use this flow for the cycle with Bayside, Fellowship Greenville and Willow

**Review by calebpanza — APPROVED** [review]

**Pull request merged**
