### PR TITLE
Deprecates Redundant Live Stream Field

### PR DESCRIPTION
**Pull request by redreceipt**
### What does this PR do, or why is it needed?

Simplifies the schema a bit. Hopefully this will be the first step in a multi-part improvement of the live streams API.

### What design trade-offs/decisions were made?

None. We're not using that field anywhere as far as I know.

### How do I test this PR?

Make sure the yellow squigly shows up in the playground I guess.

### What automated tests did you write?

None.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes [tag-issues-here]
- [x] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by conrad-vanl** [comment]
Throwing this @vinnyjth's way to confirm this is a 👍 schema change

**Comment by vinnyjth** [comment]
@redreceipt Maybe we need to talk more 🙃I don't think this is depreciated. We don't query for this field in the app, currently, but it's a field we've used in the past and I can see us use again to check if a specific content item is live.

**Comment by vinnyjth** [comment]
I'm open to hearing about why you think we should depreciate it :D

**Comment by redreceipt** [comment]
Just trying to clean up the confusing live stream logic flow. Thought this was a good first step. You can always get the exact same thing with no extra cost by querying `liveStreams` and comparing the ID.

**Comment by vinnyjth** [comment]
Let's see if we can clean up the `dataSources` first, and then clean up the schema to match :) I think this unidirectionality is fine and useful. I think Willow might use this field, also.

**Pull request closed without merging**
