### PR TITLE
chore: cherry pick of android button fix

### PR DESCRIPTION
**Pull request by nlewis84**
This is a cherry pick of a fix from master. https://github.com/ApollosProject/apollos-apps/pull/2578

### CODE REVIEW

**Comment by vinnyjth** [comment]
looks like we need to update snaps

**Review by redreceipt — APPROVED** [review]

**Comment by nlewis84** [comment]
@vinnyjth I think tests are broken on the CI. This is testing backend packages and not front end packages. Let me see if if I can figure this out.

**Comment by nlewis84** [comment]
Ahh, yeah because it is matching all packages in the `packages` folder and we have front and backend packages there on this branch. I'm going to see if I can adjust that script to only test folders that have `ui` in the title

**Comment by nlewis84** [comment]
@vinnyjth The script now only targets directories in the `packages` folder that start with `apollos-ui`. Let me know if you are down with this change.

**Pull request merged**
