### PR TITLE
fix: Close search modal when tapping on an item

### PR DESCRIPTION
**Pull request by vinnyjth**
Need to get a discussion going here. Current approach works well but is a bit of a hack. 

To test, `BRANCH=search-connected yarn app`

### CODE REVIEW

**Comment by redreceipt** [comment]
yea don't love this. @conrad-vanl didn't you suggest something about `route.params` or something?

**Comment by vinnyjth** [comment]
@redreceipt @conrad-vanl I tried moving the modal to the root, and then moving the modal inline with the tabs, and then moving the modal inline with the Home tab itself. Same behavior in all three places.

**Comment by redreceipt** [comment]
@vinnyjth what's the branch called? I don't think `search-connected` is right and I don't see any relevant draft PRs

Screen Shot 2021-06-09 at 11 52 54 AM

**Comment by vinnyjth** [comment]
Looks like it was merged 😬 
https://github.com/ApollosProject/apollos-templates/pulls?q=is%3Apr+is%3Aclosed

**Comment by redreceipt** [comment]
Oh cool. Guess the core PR wasn’t necessary so this should work with master.

**Comment by redreceipt** [comment]
We've done goofier things with nav than this. I'm gonna test and approve and we can circle back around later if the UX is too annoying or we get a better idea.

**Review by redreceipt — APPROVED** [review]

**Pull request merged**
