### PR TITLE
creates theme file without middle step

### PR DESCRIPTION
**Pull request by redreceipt**
## ✏️ Description

An apostrophe in the `$THEME` variable screws up storing it inside the `.env`. This simply creates the file instead of doing it in a later step.

## 🔬 To Test
1. Run `scripts/setup-app.sh`
2.

## 📸 Screenshots

Screenshot 2023-02-24 at 9 53 50 AM

## 📝 Checklist

- [x] I have performed a self-review of my code
- [x] I have tested my code works in the project (nothing breaks)
- [x] I have commented my code in hard-to-understand areas
- [x] New and existing tests and linting pass locally with my changes
- [x] I have made corresponding changes to the documentation (new envs?)
- [x] For PR's with design updates/changes, I have consulted with the product designer and made all necessary adjustments in Figma

### CODE REVIEW

**Review by vinnyjth — CHANGES_REQUESTED** [review]
@redreceipt Looking great - I should have done this from the get go. 

We'll also need to change the script names inside the bitrise.yml file.

**Comment by redreceipt** [comment]
@vinnyjth done

**Comment by vinnyjth** [comment]
@redreceipt wdyt about dropping the numbers from the scripts? might save us time refactoring in the future.

**Review by vinnyjth — APPROVED** [review]

**Comment by redreceipt** [comment]
I honestly see the need for separate scripts at all :) but if they’re separate I like the numbers to tell us what order they are supposed to run in.

**Pull request merged**
