### PR TITLE
generates play store graphics and metadata

### PR DESCRIPTION
**Pull request by redreceipt**
## ✏️ Description

First step in generating and uploading metadata at build time. This will generate the Play Store icon and feature graphic as well as title and description of the app. They will match the icon and wordmark provided by the client.

## 🔬 To Test
1. run `scripts/setup-app.sh` and `scripts/deploy-android.sh`

## 📸 Screenshots

Screenshot 2023-01-15 at 2 46 30 PM

## 📝 Checklist

- [x] I have performed a self-review of my code
- [x] I have tested my code works in the project (nothing breaks)
- [x] I have commented my code in hard-to-understand areas
- [x] New and existing tests and linting pass locally with my changes
- [x] I have made corresponding changes to the documentation (new envs?)
- [x] For PR's with design updates/changes, I have consulted with the product designer and made all necessary adjustments in Figma

### CODE REVIEW

**Review by calebpanza — CHANGES_REQUESTED** [review]
The short and long descriptions do not match what's currently in Google Play. Can we get this updated so that each church can handle their own copy individually? The current copy for Chase Oaks (who I tested with) seems rather intentional and I wouldn't want to introduce this as a step backwards for their listing

CleanShot 2023-01-17 at 13 27 08


Current Short Description

> The Chase Oaks Church App will keep you connected to Chase Oaks while on the go!

Current Full Description

> Welcome to the official Chase Oaks Church App.
>
> The Chase Oaks Church App will keep you connected to Chase Oaks while you're on the go! The app features both video and audio of our latest sermon series and sermon-based studies to help you go deeper with others after each week's message. It also keeps you informed of the latest stories, news, and events at Chase Oaks. After you've enjoyed the content, you can share it with your friends via Twitter, Facebook, or email.
> 
> For more information about Chase Oaks, please visit www.chaseoaks.org.
> 
> The Chase Oaks Church App was created with the Apollos Project.

**Comment by redreceipt** [comment]
Yea we can do that. I'll just make an config variable we can store in the DB.

**Comment by redreceipt** [comment]
@calebpanza this is ready again. I went ahead and filled in Chase Oaks in the DB

**Review by calebpanza — APPROVED** [review]
This is awesome!

**Pull request merged**
