### PR TITLE
feat: Allows Action URLs to be Authenticated

### PR DESCRIPTION
**Pull request by redreceipt**
This will use the Rock token to authenticate URLs clicked through a feature

### CODE REVIEW

**Comment by redreceipt** [comment]
@vinnyjth this is what @camrun91 needs to get done what he's trying to. I don't love that Authed Web Browser API to begin with so if there's a better rewrite we should do instead of continuing to hack on it, I'm all for it.

**Review by vinnyjth — CHANGES_REQUESTED** [review]
Looks good! You'll want to add `OPEN_AUTHENTICATED_URL` to the correct `enum` in the schema as well.

**Comment by vinnyjth** [comment]
yah - what I've done for other apps is this: https://github.com/lcbc-digital/ephesus/blob/master/apolloschurchapp/src/tabs/home/Home.js#L52-L56

It's always made sense b/c we have already had other custom actions. It would be great if the API of the Authed Web Browser was better, so you could `{ ...relatedNode }` into the passed props, and then add `withRockUser` to the `Url` type

**Comment by redreceipt** [comment]
alright @vinnyjth added

**Review by vinnyjth — APPROVED** [review]

**Pull request merged**
