### PR TITLE
chore: Refactor horizontal card list as functional component

### PR DESCRIPTION
**Pull request by vinnyjth**
## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
@vinnyjth you want me to review this?

**Comment by conrad-vanl** [comment]
I like this :)

**Comment by vinnyjth** [comment]
@redreceipt This is low priority, and needs it's merge conflicts addressed, and then I think it can be merged.

**Comment by redreceipt** [comment]
@vinnyjth This ready for review?

**Comment by conrad-vanl** [comment]
> @vinnyjth This ready for review?

**Comment by vinnyjth** [comment]
No, it needs to have it's merge conflicts addressed first. We can scrap it, it's just some cleanup

**Pull request closed without merging**
