### PR TITLE
chore: makes dark mode graphics optional

### PR DESCRIPTION
**Pull request by redreceipt**
its optional in code, this just mimics that in the setup

### CODE REVIEW

**Comment by vinnyjth** [comment]
This is great but they aren't optional in code :/

**Comment by vinnyjth** [comment]
Pardon my phone screenshot

image

I would love to make them optional but for all three apps I ported last week the "light" graphics were unacceptable in dark mode.

**Comment by redreceipt** [comment]
> This is great but they aren't optional in code :/

you're right. what about my latest change?

**Comment by redreceipt** [comment]
we'll leave them required

**Pull request closed without merging**
