### PR TITLE
fixes content navigation

### PR DESCRIPTION
**Pull request by redreceipt**
this was my fault...

https://user-images.githubusercontent.com/2659478/204360713-5a83f490-bc03-4497-bd02-4a4a16cbee1a.mp4

### CODE REVIEW

**Review by vinnyjth — APPROVED** [review]

**Comment by calebpanza** [comment]
@redreceipt I added a [`ScreenNames` enum](https://github.com/ApollosProject/apollos-apps/blob/master/templates/mobile/src/screens/ScreenNames.js) for these kinds of scenarios. While we're at it, might be worth adding the `ContentNavigator` key to this list.

**Review by calebpanza — APPROVED** [review]

**Comment by redreceipt** [comment]
what does that enum get us that a unique string doesn't get us? we'd still have to go through and change the enum references all over the codebase, no?

**Comment by redreceipt** [comment]
I take that back, it saves us from screen typos. wouldn't have helped with this particular bug but I can see how it would save us from others. useful if we're using typescript but an undefined screen enum name wouldn't show up until run time in plain ol javascript I think.

**Comment by calebpanza** [comment]
Yeah it's just utilizing hard references vs. strings. Would have saved us in this case cause you would be able to update the Screen Value while keeping the reference the same and everything would have worked. But we can save that for whenever we get around to migrating Content Single to UI kit 2.0

**Comment by redreceipt** [comment]
oh yea good call

**Pull request merged**
