### PR TITLE
Adds Pull to refetch on Features feed

### PR DESCRIPTION
**Pull request by vinnyjth**
### What does this PR do, or why is it needed?

This PR has made a few notable changes to add pull to refetch. 

1. Enables the `FeedView` to accept loading state data directly, rather than having to ignore the `loading` prop. 

2. Adds a `refetchRef` method the FeaturesFeed that collects all the `refetch` functions from each of the children, making sure not to collect any single ref more than once. 

### What design trade-offs/decisions were made?

I'm not in love with the `refetchRef` concept. However, I don't see any better options besides building a `Provider` to handle this, which seems overkill. At least `refetchRef` is based on an established react pattern. Open to suggestions. 

### How do I test this PR?

1. Pull down this PR, link repos, boot the app.
2. Pull down from the home feed, the feed should refetch and you can can confirm in the API console that new data is indeed loading. 

### What automated tests did you write?

New tests where appropriate. 

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by conrad-vanl** [comment]
Q: the passing of the `refetchRef` is so that you can refetch all of the child queries, right? Would it not be enough to just refetch the parent-most query?

**Comment by vinnyjth** [comment]
Q: the passing of the refetchRef is so that you can refetch all of the child queries, right? Would it not be enough to just refetch the parent-most query?

It won't because none of the props of the child features will change. I tried that route first, you can test  by changing this line https://github.com/ApollosProject/apollos-apps/pull/1437/files#diff-e47c1b17d119b8039f445d030628658aR69 to `refetch={refetch}`

**Comment by burkeshartsis** [comment]
@vinnyjth if you are looking to force a change on the children try passing something (anything?) into [`extraData`](https://reactnative.dev/docs/flatlist#extradata)

**Comment by vinnyjth** [comment]
@burkeshartsis I don't think that will work, because Apollo will only refetch if the a piece of data used in the query variables changes. I can try though.

**Comment by conrad-vanl** [comment]
@vinnyjth so it's not enough to set the `fetchPolicy` to `cache-and-network` and then to `refetch` the parent component?

Would a `refetchQueries` type of call that is outside of the component props landscape be cleaner? Probably not just a thought.

**Comment by vinnyjth** [comment]
> @vinnyjth so it's not enough to set the fetchPolicy to cache-and-network and then to refetch the parent component?

Correct. That was my first stop, but because the `featureId`s of the children never change, the parent query would be refetched but the children would remain untouched. 

> Would a refetchQueries type of call that is outside of the component props landscape be cleaner? Probably not just a thought.

I thought about that! It's probably possible, but it would be harder to extend, if you added a custom component you would have to somehow get your query into that `refetchQueries` array. At least with this route you can opt to inject your `refetch` by calling that `refetchRef` function, or not if you don't care....

**Comment by conrad-vanl** [comment]
Oh hey... @vinnyjth I thought of an error on this. What happens if a feature is removed? Like it refreshes and the feature is no longer in the feed? It will still exist in the `this.refetchFunctions` object and throw an error when you pull to refresh again, since that component no longer exists?

**Comment by vinnyjth** [comment]
>  What happens if a feature is removed? Like it refreshes and the feature is no longer in the feed? 

This shouldn't shouldn't happen under normal circumstances, but I can totally see it as a possibility in the feature. Right now an API deployment with a new config.yml is the only way this condition could arrise. 

> It will still exist in the this.refetchFunctions object and throw an error when you pull to refresh again, since that component no longer exists?

I'm honestly not sure what will happen, but I think it's worth trying to find a way to reproduce and at least know the consequences for.  I have some guesses, either ....

An error will be thrown and silently ignored because those refetch promises aren't awaited
An error will be thrown and it will break the feed, only fixed by closing and opening the app (scary!)
The refetch will point to the new component, with a new data to be pulled. Refetch will be called twice with what imagine will be minimal consequences. 

Good callout, I'll test now before we merge.

**Pull request merged**
