### PR TITLE
fix: Daily Scripture Navigation

### PR DESCRIPTION
**Pull request by calebpanza**
## ✏️ Description
In a previous PR, we introduced a custom Tab Type for Daily Habits. This PR expands on that to resolve an issue where the Scripture Experience was not navigating to the correct component.

## 🔬 To Test
1. Run a local instance of the Apollos Cluster using [this PR](https://github.com/ApollosProject/apollos-cluster/pull/371#pullrequestreview-1181841396)
2. Run the Apollos app in a sim (`yarn && yarn start` then `yarn ios`)
3. Navigate to the "Daily" tab and scroll down until you see the "Scripture" card
4. Tap on it and you should see an actual Content Item pop up this time

### Before the Fix
https://user-images.githubusercontent.com/45076058/202079450-0a62933a-edf4-4f2f-8824-fbe798e4c131.mp4

### After the Fix
https://user-images.githubusercontent.com/45076058/202079239-9355c9a0-90f9-4e94-a4c9-d4071295e36f.mp4

## ⚠️ To-do Before Merge

- [x] Ensure the [Cluster PR](https://github.com/ApollosProject/apollos-cluster/pull/371#pullrequestreview-1181841396) is merged
- [x] Ensure that #2766  is merged

## 📝 Checklist

- [x] I have performed a self-review of my code
- [x] I have tested my code works in the project (nothing breaks)
- [x] I have commented my code in hard-to-understand areas
- [x] New and existing tests and linting pass locally with my changes
- [x] I have made corresponding changes to the documentation (new envs?)

### CODE REVIEW

**Review by jordanwade — COMMENTED** [review]
This is what I see when clicking that scripture card. Is that expected or should I actually see a bible verse? 

image

**Comment by conrad-vanl** [comment]
@calebpanza how does this get marked as "complete"? just opening up the content item?

**Comment by calebpanza** [comment]
> how does this get marked as "complete"?

@conrad-vanl I can confirm with with @camrun91 but I believe that we're sending interaction events to the dB for when a user **views** a **scripture**. In order to get the check mark, you have to have viewed at least 1 of the Scripture Features attached to the Content Item on that given day.

in the current Demo App, we don't technically have the Content Items set up correctly for you to actually achieve a finished state on this. We just haven't had the bandwidth to get it set up to be an "accurate" example

**Review by jordanwade — APPROVED** [review]
Looks good, just needs to have a few tests to get the Ci to pass.

**Pull request merged**
