### PR TITLE
chore: adds xs size avatar

### PR DESCRIPTION
**Pull request by redreceipt**
test with `BRANCH=xs yarn app`
Screen Shot 2021-09-28 at 10 43 18 AM

### CODE REVIEW

**Comment by conrad-vanl** [comment]
@redreceipt why is the avatar still not circular?

**Comment by conrad-vanl** [comment]
Screen Shot 2021-09-28 at 10 07 42 AM

**Comment by redreceipt** [comment]
yea I'm not sure :/ we should fix but maybe in a different PR so it doesn't hold up FNWA launch

**Comment by nlewis84** [comment]
Maybe this is causing it? https://github.com/ApollosProject/apollos-templates/blob/9bcaafbbb4d88eec9f808c959a51b082579345ad/apolloschurchapp/src/tabs/index.js#L54

**Review by conrad-vanl — APPROVED** [review]

**Pull request merged**
