### PR TITLE
Moves User Web View to Packages

### PR DESCRIPTION
**Pull request by redreceipt**
### What does this PR do, or why is it needed?

Step one of two PRs to move the user web view out of the app package. Next step will be to reference the new one in the template package. This also cleans up a bit and does everything in #1074

### What design trade-offs/decisions were made?

- Instead of using `NavigationService`, you just pass in `navigation`.
- Exports context instead of individual provider and consumer
- Removed deprecated query field and replaced with new one

### How do I test this PR?

Look at the story

### What automated tests did you write?

Added some coverage.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes [tag-issues-here]
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by conrad-vanl** [comment]
@redreceipt i tried to mention this in the other PR, but we do have a [`RockAuthedWebBrowser`](https://github.com/ApollosProject/apollos-apps/tree/master/packages/apollos-ui-connected/src/RockAuthedWebBrowser) already in this package that I think we should use here. It's the same thing right?

**Comment by redreceipt** [comment]
> @redreceipt i tried to mention this in the other PR, but we do have a [`RockAuthedWebBrowser`](https://github.com/ApollosProject/apollos-apps/tree/master/packages/apollos-ui-connected/src/RockAuthedWebBrowser) already in this package that I think we should use here. It's the same thing right?

That's an inappbrowser

**Comment by conrad-vanl** [comment]
@redreceipt ahhhhhh now that's confusing 😉 Sorry about that.

So this is a "WebView" - what's the difference? It's technically a browser...that's in the app. So what's the difference in use case? What does this do that RockAuthedWebBrowser doesn't?

I think this is opportunity to provide clarity and create something that's easier to understand. If we had a `RockAuthedWebBrowser` and `UserWebView` - as a developer by those names I have no clue what the difference is. If we had `RockAuthedWebBrowser` and `RockAuthedWebView` ... that might give a little clarity (as then the only distinction is `Browser` vs `View`).

Thoughts on how we can better provide that clarity?

**Comment by redreceipt** [comment]
I like that idea. I'll go with that unless @vinnyjth has other thoughts.

**Comment by vinnyjth** [comment]
> If we had RockAuthedWebBrowser and RockAuthedWebView ... that might give a little clarity (as then the only distinction is Browser vs View).

💯

**Comment by redreceipt** [comment]
Ok how about now

**Pull request merged**
