### PR TITLE
Adds Notifications Toggle

### PR DESCRIPTION
**Pull request by redreceipt**
## DESCRIPTION

Screen Shot 2019-06-25 at 11 24 45 AM

### What does this PR do, or why is it needed?

This will give us the ability to toggle push notifications in app

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [#809 ]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
@vinnyjth how do I use the `ui-notifications` queries? None of these are showing up in the schema
Screen Shot 2019-06-25 at 11 44 11 AM

**Comment by vinnyjth** [comment]
@redreceipt Those are all client side. You'll see the resolvers for them inside the `store` for that module.

**Comment by redreceipt** [comment]
gotcha, what exactly do the two functions here do? Do I need to figure out how to disable notifications? Can't tell if your functions already do that with Onesignal.

Screen Shot 2019-06-25 at 12 15 42 PM

**Comment by vinnyjth** [comment]
@redreceipt We don't currently have a way to enable or disable push notifications. You'll need the update the API here https://github.com/ApollosProject/apollos-prototype/blob/master/packages/apollos-data-connector-onesignal/src/data-source.js#L19 to correctly set if a user has enabled push notifications. I don't have an answer for you as to "how" but it should probably be a setting that you set in OneSignal or Rock.

**Comment by redreceipt** [comment]
Ok so here's the game plan:
1. Add `notificationsEnabled` attribute in Rock (include in plugin)
2. Set to `true` in onboarding and the new settings toggle
3. Add `disableNotifications` to our API

Bonus Rock work:
- Have communication service check that attribute first (include in plugin)
- Have communication UI check first (include in plugin)

Thoughts??? @richarddubay missing anything?

**Comment by redreceipt** [comment]
Currently waiting on an answer from Spark about adding an `AllowPushNotifications` attribute to core Rock.

**Comment by richarddubay** [comment]
@redreceipt I think this sounds good. Right now all the transport does (pretty much) is send off the devices to OneSignal and it either sends a notification or not depending on if the device exists there. So the transport will just have to check for the attribute and remove anyone from the list of people it's sending to before it sends it off to OneSignal for processing. 

I like the idea of adding a core attribute so that the communication block can be updated as well. Great stuff.

**Comment by redreceipt** [comment]
@vinnyjth so for now until Rock decides what to do, we could just add an extended attribute called `ApollosNotificationsAllowed`, what do you think?

**Comment by redreceipt** [comment]
@frankgrand is speaking with Spark about getting a `NotificationsAllowed` top level data field on a person similar to SMS so I say we wait and see what they say before adding a custom attribute.

**Comment by redreceipt** [comment]
@vinnyjth can we add attributes with the plugin?

**Pull request closed without merging**
