### PR TITLE
feat: Feature caching support. 

### PR DESCRIPTION
**Pull request by vinnyjth**
### What does this PR do, or why is it needed?

This is something that LCBC and Grace (and possibly the other church apps) are already doing, or should be doing. it allows us to specify specific algorithms as "cache busting" so we don't pick them up in in `fastly`.

https://github.com/lcbc-digital/ephesus/blob/master/apollos-church-api/src/data/Feature.js#L90

### How do I test this PR?

No great way to test this. One option would be to fetch the `userFeedFeatures` feed in `apollos-church-api` and then compare the cache times when fetching each of the individual `nodes`.

```
query feed {
  userFeedFeatures {
    id
    __typename
  }
}

query node {
  node(id:""){
    id
    ... on ActionListFeature {
      actions {
        id
        title
      }
    }
    ... on VerticalCardListFeature {
      cards {
        id
        title
      }
    }    
  }
}
```

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
server is crashing for me on templates master, ever seen this one?

Screen Shot 2020-09-28 at 3 06 07 PM

**Comment by vinnyjth** [comment]
I haven’t, but Rich has. Try restarting redis? Or check your connection string in your .env?

**Comment by redreceipt** [comment]
does this look relevant?
Screen Shot 2020-09-28 at 3 13 27 PM

**Comment by vinnyjth** [comment]
@redreceipt Sure does! Easy fix....

**Comment by vinnyjth** [comment]
Actually I take that back. That might have been caused by that ID PR, but I'm not sure.

**Comment by vinnyjth** [comment]
@redreceipt I snuck a fix into this PR

**Review by redreceipt — APPROVED** [review]

**Pull request merged**
