### PR TITLE
fix: Nest BottomSheetModalProvider

### PR DESCRIPTION
**Pull request by conrad-vanl**
Fixes a bug in master where `BottomSheet`s don't get Theme.

### CODE REVIEW

**Review by nlewis84 — APPROVED** [review]
🎒

**Review by redreceipt — APPROVED** [review]

**Comment by redreceipt** [comment]
we should probably cover that thing with snaps

**Comment by nlewis84** [comment]
I'll take care of snaps

**Comment by redreceipt** [comment]
turn off auto merge just to make sure the changes aren't a ton. they shouldn't be.

**Comment by nlewis84** [comment]
Just analytics. Good to merge @redreceipt?

**Comment by redreceipt** [comment]
yep, not sure why those changed but 🤷‍♂️ looks fine to me

**Pull request merged**
