### PR TITLE
test/no-video-routing

### PR DESCRIPTION
**Pull request by dsilva609**
## 🔬 To Test
1. Go to a content series that has no videos in it (Item 5 in apollos_demo is a good one)
2. Press the hardware back button
3. It should send you back the the previous screen instead of exiting out of the app

## 📝 Checklist

- [ ] I have performed a self-review of my code
- [ ] I have tested my code works in the project (nothing breaks)
- [ ] I have commented my code in hard-to-understand areas
- [ ] New and existing tests and linting pass locally with my changes
- [ ] I have made corresponding changes to the documentation (new envs?)
- [ ] For PR's with design updates/changes, I have consulted with the product designer and made all necessary adjustments in Figma

### CODE REVIEW

**Comment by vinnyjth** [comment]
@dsilva609 @calebpanza would it be better to solve this by not allowing you to navigate to items with no video? What's the value in visiting one of these items?

**Comment by calebpanza** [comment]
@vinnyjth that's fine, but it still doesn't resolve the underlying issue and we'll have to figure this out at some point. Per our testing, the only way to get _any_ screen within this ContentSingle navigation stack to work properly is to render an input type (like TextInput) which means as we expand the feature offerings of TV, we're gonna run into the problem again

**Comment by vinnyjth** [comment]
@calebpanza totally agree, would be great to know what's causing this! 

but even if we fix this we should really avoid navigating to a content with no video content :) hopefully we could avoid rendering it's card to begin with.

**Comment by dsilva609** [comment]
Obsolete with newer pull request

**Pull request closed without merging**
