### PR TITLE
Convert Data Connectors' Functions to Using Named Arguments

### PR DESCRIPTION
**Pull request by erikkgagewhitt**
### What does this PR do, or why is it needed?

Converts the data-connector packages from using positional arguments to named arguments across the board.

Exceptions include any functions which come from packages outside the data-connector packages including other apollos packages and the getFromIds function as it is required (at least for now) to use positional arguments.

### How do I test this PR?

Not totally sure. I used the existing automated tests to ensure nothing had broken as a result of the conversion.

### What automated tests did you write?

Many tests/snapshots were updated in order to reflect the above changes.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [x] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by conrad-vanl** [comment]
Sad that this is so old and getting stale. @vinnyjth are we trashing this?

**Comment by vinnyjth** [comment]
@conrad-vanl So far the conflicts look very easy to resolve, so I'm fine keeping it around for a bit longer. I would love to get it merged but I need to take a day or two to sit down and do some final polish first to make sure the API is hyper polished and I know how it will affect CF / Newspring

**Comment by conrad-vanl** [comment]
@vinnyjth we should close this if it's not going to be merged

**Comment by vinnyjth** [comment]
😭

**Pull request closed without merging**
