### PR TITLE
Removes interaction sessions

### PR DESCRIPTION
**Pull request by redreceipt**
### What does this PR do, or why is it needed?

Removes sessions from node interactions because our sessions have the potential of being invalid, causing 500 errors.

### What design trade-offs/decisions were made?

None.

### How do I test this PR?

Make some interactions

### What automated tests did you write?

None

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes [tag-issues-here]
- [x] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
Tested and looks good 👍

**Comment by vinnyjth** [comment]
@redreceipt can you take a look at the tests and fix whatever is broken? Probably just need updated snaps on the API.

**Comment by redreceipt** [comment]
Ok good now

—
Michael

**Comment by vinnyjth** [comment]
You might need to back out those prayer snaps - they generate wrong locally. I need to push a PR to fix them.

**Pull request merged**
