### PR TITLE
fix: Add state for loading between fetching

### PR DESCRIPTION
**Pull request by tomthornton**
For some reason, the `loading` prop from the Apollo HOC isn't updating whenever a feed view is refreshed. This adds state to the FeedView itself in order to get the desired effect.  Also, if there is an error in refetching the loading state will be set `false`

### CODE REVIEW

**Comment by redreceipt** [comment]
I don't fully understand the problem, could you possibly post a GIF displaying what this is fixing?

**Comment by tomthornton** [comment]
@redreceipt the loading indicator is immediately dismissed when refreshed. This shows and accurate loading indicator.

**Before**

https://user-images.githubusercontent.com/40962668/135520383-31486d96-be83-4a9a-a851-fed48b326826.mp4

**After**
https://user-images.githubusercontent.com/40962668/135520520-8dbef40c-6bfe-4ce7-899d-c731a0e9a07f.mp4

**Comment by redreceipt** [comment]
nice! yea fix tests and then I'll approve

**Comment by redreceipt** [comment]
snapshots are failing here

**Comment by tomthornton** [comment]
@vinnyjth @redreceipt is it okay to remove the `isLoading` test from components who use the `FeedView`? Since the `isLoading` prop is now being handled within `FeedView` its self there doesn't need to be tests outside. Or we could figure out why `isLoading` isn't updating in the first place but I couldn't figure it out.

**Comment by redreceipt** [comment]
I'm cool with it as long as it doesn't make coverage go down. Codecov will tell us.

**Comment by redreceipt** [comment]
I'm seeing strange animation and behavior with this one

Kapture 2021-12-06 at 19 53 12

**Pull request closed without merging**
