### PR TITLE
fix: child and siblings pulling inactive items

### PR DESCRIPTION
**Pull request by vinnyjth**

### CODE REVIEW

**Comment by vinnyjth** [comment]
image

**Review by nlewis84 — COMMENTED** [review]
🎒

**Comment by vinnyjth** [comment]
@nlewis84 I have no idea what your emoji means 😂

**Review by nlewis84 — APPROVED** [review]
Backpack, like Dora the Explorer going on a trip. Ship it! Sorry I thought I approved it. 😬 😂 

This change makes sense and I'm seeing correct data locally when I tested this out.

**Pull request merged**
