### PR TITLE
chore: converted ProtectedRoute to functional component

### PR DESCRIPTION
**Pull request by redreceipt**

### CODE REVIEW

**Review by conrad-vanl — COMMENTED** [review]
@redreceipt do these snapshot changes look right to you? Seems like pretty big snap changes for just converting to functional component

**Comment by redreceipt** [comment]
> @redreceipt do these snapshot changes look right to you? Seems like pretty big snap changes for just converting to functional component

It changed a lot because I'm using the new navigation test utility. It's wrapped in a navigator screen now.

**Comment by redreceipt** [comment]
@conrad-vanl I think the snap changes here are fine, see my previous comment

**Comment by vinnyjth** [comment]
I did something similar in the `ui-authentication` branch, so I likely won't review this unless we see an urgent need for it (the code it's pointing at will soon be deprecated)

**Pull request closed without merging**
