### PR TITLE
moves app to use fastly

### PR DESCRIPTION
**Pull request by redreceipt**
## ✏️ Description

Uses our new Fastly API endpoint. 

## 🔬 To Test
1. Click around on a couple of different churches and make sure there's no overlap

## 📸 Screenshots

You can see here the endpoint in action. The first call I make is to get the Newspring campuses. The cache misses. Then I do it again and the cache hits. Then I do it for a different church and it misses like it should and returns the right campuses.

```sh
~ % curl -H "x-church: newspring" "https://production.apollos.app/?query=\{campuses\{name\}\}" -v
*   Trying 151.101.2.132:443...
* Connected to production.apollos.app (151.101.2.132) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=production.apollos.app
*  start date: Dec 20 13:13:50 2022 GMT
*  expire date: Mar 20 13:13:49 2023 GMT
*  subjectAltName: host "production.apollos.app" matched cert's "production.apollos.app"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /?query={campuses{name}}]
* h2h3 [:scheme: https]
* h2h3 [:authority: production.apollos.app]
* h2h3 [user-agent: curl/7.85.0]
* h2h3 [accept: */*]
* h2h3 [x-church: newspring]
* Using Stream ID: 1 (easy handle 0x12180b000)
> GET /?query={campuses{name}} HTTP/2
> Host: production.apollos.app
> user-agent: curl/7.85.0
> accept: */*
> x-church: newspring
>
< HTTP/2 200
< server: Cowboy
< x-powered-by: Express
< access-control-allow-origin: *
< content-type: application/json; charset=utf-8
< cache-control: max-age=3600, public
< etag: W/"1ce-ILT04R4VwCTnU+LPBSSJfz3ilMA"
< via: 1.1 vegur, 1.1 varnish
< accept-ranges: bytes
< date: Wed, 21 Dec 2022 17:29:11 GMT
< age: 0
< x-served-by: cache-fty21364-FTY
< x-cache: MISS
< x-cache-hits: 0
< x-timer: S1671643751.140980,VS0,VE167
< vary: x-church
< content-length: 462
<
{"data":{"campuses":[{"name":"Hilton Head"},{"name":"Myrtle Beach"},{"name":"Lake Wylie"},{"name":"Charleston"},{"name":"Columbia"},{"name":"Greenwood"},{"name":"Aiken"},{"name":"Greenville"},{"name":"Anderson"},{"name":"Support Center"},{"name":"Florence"},{"name":"Clemson"},{"name":"Northeast Columbia"},{"name":"Powdersville"},{"name":"Spartanburg"},{"name":"Web"}]},"extensions":{"cacheControl":{"version":1,"hints":[{"path":["campuses"],"maxAge":3600}]}}}
* Connection #0 to host production.apollos.app left intact
~ % curl -H "x-church: newspring" "https://production.apollos.app/?query=\{campuses\{name\}\}" -v
*   Trying 151.101.194.132:443...
* Connected to production.apollos.app (151.101.194.132) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=production.apollos.app
*  start date: Dec 20 13:13:50 2022 GMT
*  expire date: Mar 20 13:13:49 2023 GMT
*  subjectAltName: host "production.apollos.app" matched cert's "production.apollos.app"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /?query={campuses{name}}]
* h2h3 [:scheme: https]
* h2h3 [:authority: production.apollos.app]
* h2h3 [user-agent: curl/7.85.0]
* h2h3 [accept: */*]
* h2h3 [x-church: newspring]
* Using Stream ID: 1 (easy handle 0x152811e00)
> GET /?query={campuses{name}} HTTP/2
> Host: production.apollos.app
> user-agent: curl/7.85.0
> accept: */*
> x-church: newspring
>
< HTTP/2 200
< server: Cowboy
< x-powered-by: Express
< access-control-allow-origin: *
< content-type: application/json; charset=utf-8
< cache-control: max-age=3600, public
< etag: W/"1ce-ILT04R4VwCTnU+LPBSSJfz3ilMA"
< via: 1.1 vegur, 1.1 varnish
< accept-ranges: bytes
< date: Wed, 21 Dec 2022 17:29:17 GMT
< age: 6
< x-served-by: cache-fty21361-FTY
< x-cache: HIT
< x-cache-hits: 1
< x-timer: S1671643757.315440,VS0,VE1
< vary: x-church
< content-length: 462
<
{"data":{"campuses":[{"name":"Hilton Head"},{"name":"Myrtle Beach"},{"name":"Lake Wylie"},{"name":"Charleston"},{"name":"Columbia"},{"name":"Greenwood"},{"name":"Aiken"},{"name":"Greenville"},{"name":"Anderson"},{"name":"Support Center"},{"name":"Florence"},{"name":"Clemson"},{"name":"Northeast Columbia"},{"name":"Powdersville"},{"name":"Spartanburg"},{"name":"Web"}]},"extensions":{"cacheControl":{"version":1,"hints":[{"path":["campuses"],"maxAge":3600}]}}}
* Connection #0 to host production.apollos.app left intact
~ % curl -H "x-church: fellowship_nwa" "https://production.apollos.app/?query=\{campuses\{name\}\}" -v
*   Trying 151.101.2.132:443...
* Connected to production.apollos.app (151.101.2.132) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=production.apollos.app
*  start date: Dec 20 13:13:50 2022 GMT
*  expire date: Mar 20 13:13:49 2023 GMT
*  subjectAltName: host "production.apollos.app" matched cert's "production.apollos.app"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /?query={campuses{name}}]
* h2h3 [:scheme: https]
* h2h3 [:authority: production.apollos.app]
* h2h3 [user-agent: curl/7.85.0]
* h2h3 [accept: */*]
* h2h3 [x-church: fellowship_nwa]
* Using Stream ID: 1 (easy handle 0x141811e00)
> GET /?query={campuses{name}} HTTP/2
> Host: production.apollos.app
> user-agent: curl/7.85.0
> accept: */*
> x-church: fellowship_nwa
>
< HTTP/2 200
< server: Cowboy
< x-powered-by: Express
< access-control-allow-origin: *
< content-type: application/json; charset=utf-8
< cache-control: max-age=3600, public
< etag: W/"f1-B/ZipRHzERSCaVEUMO/82ln4Gf4"
< via: 1.1 vegur, 1.1 varnish
< accept-ranges: bytes
< date: Wed, 21 Dec 2022 17:29:33 GMT
< age: 0
< x-served-by: cache-fty21373-FTY
< x-cache: MISS
< x-cache-hits: 0
< x-timer: S1671643773.250452,VS0,VE156
< vary: x-church
< content-length: 241
<
{"data":{"campuses":[{"name":"Fellowship Rogers"},{"name":"Fellowship Mosaic"},{"name":"Fellowship Fayetteville"},{"name":"Fellowship Bentonville"}]},"extensions":{"cacheControl":{"version":1,"hints":[{"path":["campuses"],"maxAge":3600}]}}}
* Connection #0 to host production.apollos.app left intact
```

## 📝 Checklist

- [x] I have performed a self-review of my code
- [x] I have tested my code works in the project (nothing breaks)
- [x] I have commented my code in hard-to-understand areas
- [x] New and existing tests and linting pass locally with my changes
- [x] I have made corresponding changes to the documentation (new envs?)
- [x] For PR's with design updates/changes, I have consulted with the product designer and made all necessary adjustments in Figma

### CODE REVIEW

**Comment by calebpanza** [comment]
Is it safe to use the Fastly endpoint when developing locally?

**Comment by redreceipt** [comment]
> Is it safe to use the Fastly endpoint when developing locally?

yep should be

**Comment by vinnyjth** [comment]
@redreceipt need to change here as well. Otherwise `errorLink` will be using a different URL .

https://github.com/ApollosProject/apollos-apps/blob/c53b258411b2ab2f368ade2d658adc9f0865ecb0/scripts/setup-app.sh#L97

**Comment by redreceipt** [comment]
Dang good catch

**Comment by redreceipt** [comment]
@vinnyjth ready

**Comment by vinnyjth** [comment]
Awesome - looking forward to getting this in the wild

**Review by vinnyjth — APPROVED** [review]

**Comment by calebpanza** [comment]
Since that URL is being used in multiple places, would it be possible/beneficial to snapshot the default generation of our Apollo links?

**Comment by redreceipt** [comment]
> Since that URL is being used in multiple places, would it be possible/beneficial to snapshot the default generation of our Apollo links?

It's only used in one place

**Pull request merged**
