### PR TITLE
fix: Automerge functionality deletes emails

### PR DESCRIPTION
**Pull request by vinnyjth**
The automerge functionality being turned on was deleting folks email address. 

This was for a few reasons. 

1. We historically pass down `email: null` when doing SMS logins (I need to explore why we do that a bit more) 
2. Prior to turning *automerge* off, we ran the code currently inside the if statement. 
3. When enabling automerge again, we choose to run the `patch` code even if we didn't need to automerge. 
4. That `patch` code ends up deleting folks emails. Hence why it's a separate operation inside the Rock UI.

### CODE REVIEW

**Comment by conrad-vanl** [comment]
We should prioritize getting this out on apps that currently have auto-merge turned on....that's chase oaks, fellowship, and.... RV?

**Comment by vinnyjth** [comment]
@conrad-vanl do you want to review it? If you review I can merge and start work on deploy.

**Comment by vinnyjth** [comment]
Here's the code prior to removing automerge (and then allowing folks to turn it back on) 

https://github.com/ApollosProject/apollos-apps/blob/a2b62f6b098fe9403f86f3003b8638a6008f2ff7/packages/apollos-data-connector-rock/src/people/data-source.js#L68-L75

**Review by redreceipt — APPROVED** [review]
nice. we probably should have done it this way to begin with.

**Comment by conrad-vanl** [comment]
@redreceipt @vinnyjth I need one of you to prioritize getting this deployed on Chase Oaks ASAP.

@redreceipt do we have any other apps in production with this error?

**Comment by redreceipt** [comment]
Anyone with auto merge turned on would have it.

**Comment by conrad-vanl** [comment]
Yeah but who do we have with auto merge that's in production?

**Comment by redreceipt** [comment]
I wish I’d recorded that somewhere :/ let me do some digging through Heroku instances. I’ll patch any one that I find and let you know.

**Pull request merged**
