### PR TITLE
chore: Adds create mobile app CLI command

### PR DESCRIPTION
**Pull request by redreceipt**
test by running `npm link` inside `packages/apollos-cli` and then running `apollos create mobile` somewhere else 🙌 

render1642484339985

### CODE REVIEW

**Comment by vinnyjth** [comment]
I think only the first space is stripped :) 

image

**Comment by vinnyjth** [comment]
🤔 

image

**Comment by redreceipt** [comment]
yea looks like the three words are messing it up. I'll fix the regex.

**Comment by redreceipt** [comment]
ok @vinnyjth should be good now

**Comment by redreceipt** [comment]
also sorry for the no PR description at first. A GIF and testing instructions are up above now. It was late and I left it in "edit" mode 😬 .

**Comment by vinnyjth** [comment]
All good! You can't fault yourself for not pushing code at 11pm on a national holiday 😂

**Pull request merged**
