### PR TITLE
chore: Storybook in apps repo

### PR DESCRIPTION
**Pull request by vinnyjth**
### What does this PR do, or why is it needed?

Biggest node here is that I didn't put the app inside the packages folder. Why? 

1. It's not a package 🤷 
2. It ensures I don't have to fight nohoist. 
3. It helps ensure we don't have to write workarounds for scripts that run across the entire `packages` folder.

### What design trade-offs/decisions were made?

I used a blank RN 63 project. It's technically not the current version of RN we currently use, but it won't matter for most purposes. I would rather be ahead of core now, and not have to upgrade down the road. 

### How do I test this PR?

From the root: 

`yarn storybook-install`
`yarn storybook`
`yarn storybook-start`

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
this should probably be a `chore` since it doesn't affect npm dependencies at all and shouldn't cause a minor version bump

**Comment by redreceipt** [comment]
this is a little confusing

Screen Shot 2020-09-16 at 3 17 18 PM

 may I suggest:

```
"storybook": "(cd ApollosStorybook && yarn && yarn start && sleep 10 & yarn ios)"
```

**Comment by redreceipt** [comment]
or else, I would probably just cd into `ApollosStorybook` dir and do everything manually like always, remembering and typing in those other commands is a lot

**Comment by vinnyjth** [comment]
> or else, I would probably just cd into ApollosStorybook dir and do everything manually like always, remembering and typing in those other commands is a lot

What if we delete the commands and encourage that as the default way of working with this repo? I'm with you, that I'll end up cd'ing and running the commands 9 times out of 10.

**Comment by redreceipt** [comment]
I don't mind a single helper command or else I'd probably forget for a split second how to get it working and run to slack

**Comment by redreceipt** [comment]
worked on the first try for me!
Screen Shot 2020-09-16 at 3 28 53 PM

**Comment by vinnyjth** [comment]
> worked on the first try for me!
> Screen Shot 2020-09-16 at 3 28 53 PM

Unbelievable!

**Comment by vinnyjth** [comment]
@redreceipt I left out `yarn start` because `yarn ios` starts a packager by itself if there's not one open.

**Review by redreceipt — APPROVED** [review]

**Pull request merged**
