### PR TITLE
feat(community): update gratitude input to match daily habit

### PR DESCRIPTION
**Pull request by dsilva609**
## ✏️ Description
- updates gratitude input in community to match the one in daily habits

## 🔬 To Test
1. Go to post a new gratitude in community
2. Should see updated input scren

## 📸 Screenshots

image
image

## 📝 Checklist

- [ ] I have performed a self-review of my code
- [ ] I have tested my code works in the project (nothing breaks)
- [ ] I have commented my code in hard-to-understand areas
- [ ] New and existing tests and linting pass locally with my changes
- [ ] I have made corresponding changes to the documentation (new envs?)
- [ ] For PR's with design updates/changes, I have consulted with the product designer and made all necessary adjustments in Figma

### CODE REVIEW

**Comment by conrad-vanl** [comment]
Is there a reason we have separate Gratitude and Prayer inputs in community and daily? (I'm not saying it's a bad thing, just curious)

**Comment by dsilva609** [comment]
> Is there a reason we have separate Gratitude and Prayer inputs in community and daily? (I'm not saying it's a bad thing, just curious)

@conrad-vanl the inputs on community were using the old design style so this change is meant to bring them up to the current one that's being used in daily

**Comment by camrun91** [comment]
I think what @conrad-vanl is asking @dsilva609 is this: Is there a reason we are not using a shared component for these two screens or why the nav can't point to the same input?

**Comment by conrad-vanl** [comment]
yeah, I'm asking @camrun91 's question

**Comment by dsilva609** [comment]
> I think what @conrad-vanl is asking @dsilva609 is this: Is there a reason we are not using a shared component for these two screens or why the nav can't point to the same input?

I might be missing something here, but these are actually using the same shared input with the only difference is that Daily is using a full "experience" navigation style and in community it's just pulling out the single input section of the experience. We could make both community and daily have the full experience flow if we wanted though.

**Comment by camrun91** [comment]
@conrad-vanl You know what the designs and stuff would call for.

**Comment by calebpanza** [comment]
I can provide more context to this on Monday.

**Review by calebpanza — APPROVED** [review]

**Pull request merged**
