### PR TITLE
MVP of Auth Refresh (instead of error) 

### PR DESCRIPTION
**Pull request by vinnyjth**
## DESCRIPTION

Screen Shot 2020-07-23 at 2 52 21 PM

Makes the following changes: 

- If an auth attempt fails because Rock denies the cooke
  1. Check to see if we have a reference to a sha1 hashed version of the cookie in Redis. 
  2. If we do, lookup the cookie and grab the User Name (stored on future logins) 
  3. With the username, fetch the UserLogin, then fetch the associated Person (wish we could do this in one step)
  4. If any of those fail, raise a Useful error to make debugging in the future easier. 

- On login
 1. Once we have a cookie, make a SHA1 version of the cookie, and use it as the key, with the value being a user's username. 

Q: Why store the username in redis instead of the PersonId? 
A: I wanted there to be some form of rock based bail out. if a user login gets changed or deleted in rock, we can properly log the user out. 

Q: So the user will be failing login, and then getting their data from redis forever? eww. 
A: Baby steps. A client change will be required to actually send a user a new cookie to use. We should get this code out as early as possible so we can start collecting cookies/usernames in Redis. 

Q: How soon will this have an impact? 
A: A user will get logged out one more time, theoretically, but any future time they login we'll track their cookie. We could add preemptive code that creates that cookie/username association on ever `getCurrentPerson` call, but that feels like overkill. 

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
@conrad-vanl I'm going to write tests for this, and then try to hack together a demo of the login failed side. Can you give it a preliminary glance over in the meantime?

**Comment by conrad-vanl** [comment]
Can @richarddubay @redreceipt or @asleepingpanda 👀  on this a little and give input from the Rock side / security aspect?

**Comment by conrad-vanl** [comment]
> Q: Why store the username in redis instead of the PersonId?
> A: I wanted there to be some form of rock based bail out. if a user login gets changed or deleted in rock, we can properly log the user out.

@vinnyjth if we used an impersonation token or a person token instead of a username would that be better from this perspective?

**Comment by conrad-vanl** [comment]
Also, will the Willow update atleast verify that we are in fact getting tokens denied from Rock? I'd hate to put this out there and still not know whether or not this will fix anything.

**Comment by vinnyjth** [comment]
@conrad-vanl It would be different. We would have the option of setting an expiration on that token directly, but I don't think a user changing their login would invalidate the impersonation token. I'm open to either option. I like the UserLogin option better, because i understand the all the implications of using UserLogin. I'm still a little weary of the ImpersonationToken, because I don't want to run into the same "they were invalidated and we don't know why" problems.


What's a person token?

**Comment by vinnyjth** [comment]
> Also, will the Willow update atleast verify that we are in fact getting tokens denied from Rock? I'd hate to put this out there and still not know whether or not this will fix anything.

Yep! The build is submitted, we are now waiting for approval. I think we can safely hold off merging this until we get data from Willow

**Comment by conrad-vanl** [comment]
Screen Shot 2020-07-23 at 3 26 39 PM

Screen Shot 2020-07-23 at 3 26 59 PM

**Comment by vinnyjth** [comment]
Oh okay - so same thing.

**Comment by redreceipt** [comment]
waiting makes sense but wanted to throw out there that even if this doesn't fix anything for our current bug, it will solve the issue where jwts will expire in 400 days and everyone is going to get logged out again.

**Comment by conrad-vanl** [comment]
@vinnyjth with this approach, why use cookies at all? Aren't they effectively not used now? Like, if the cookie is invalid, we just circumvent the cookie. Why still use it at all?

**Comment by vinnyjth** [comment]
> @vinnyjth with this approach, why use cookies at all? Aren't they effectively not used now? Like, if the cookie is invalid, we just circumvent the cookie. Why still use it at all?

Because it is a drop in update that doesn't require any architectural change. Also, we can patch this version to send updated cookies to the client in the future (so that cookies, in some sense, do matter).

That said, I understand the sentiment here. I would like to talk to Jon about moving to People tokens long term (replacing cookies altogether with people tokens) and removing this "retry" logic.

**Comment by vinnyjth** [comment]
@conrad-vanl I think the next step, no matter what, is to equip the client to update the auth token that it stores. That's going to be a requirement if we want to change what is stored in auth token, no matter what direction we go, long term. I'm hoping that this PR will, for now, stop the bleeding.

**Comment by vinnyjth** [comment]
Added tests, and so I'm now considering this "ready for review"

**Comment by conrad-vanl** [comment]
FYI - the above comment was 100% meant to be suggestive and open for discussion and not "this is what we're doing" ;-) 

I'm not sure of the best solution, I'm just trying to figure out what's going to help us the most, introduce the least amount of debt, and be lowest risk. Arguably, what I'm proposing could be looked at as more debt, or less debt. I'm not really sure.

**Comment by vinnyjth** [comment]
> FYI - the above comment was 100% meant to be suggestive and open for discussion and not "this is what we're doing" ;-)

I'm all for your suggestion :) I think it's slightly more vulnerable from a security standpoint (someone could, if they know the `SECRET`, login as anyone if they knew their ID, or could cycle through IDs sequentially. 

I like the simplicity of your approach, and I think beyond being slightly more performant it will function identically. 

I need to jump back over to integration work, but when I wrap up that I can jump back over here and rewrite this PR.

**Comment by vinnyjth** [comment]
In terms of debt, I think both approaches have equal debt. They both touch the codebase in the same way, at the same places. I think both have logic that is easy to follow. The branches paths of my PR are arguably a little more complex, but I hope I've mitigated through clear annotation and specific error messages.

**Comment by vinnyjth** [comment]
@conrad-vanl I just realized one big issue with the `personId` approach. It will become inaccurate if a user is deduped post login. That _shouldn't_ happen, now that we try and de-dup up front, but if a de-dup is performed after login, a user will never end up associated with their new profile until they logout and login again.

**Comment by conrad-vanl** [comment]
@vinnyjth based on your explanation I'm a fan of your `username` approach then. If you get this PR in that state and tag me I'll do the final review so we can merge.

**Comment by vinnyjth** [comment]
@conrad-vanl We're back at the "username" state.

**Pull request merged**
