### PR TITLE
feat: ui-authentication / (cluster authentication) 

### PR DESCRIPTION
**Pull request by vinnyjth**
To test `BRANCH=ui-authentication yarn app`

This is a refactor / duplication of `ui-auth` that is built for the next-gen features currently live in apollos-cluster.

### CODE REVIEW

**Comment by vinnyjth** [comment]
@conrad-vanl If you're interested, this is in a good spot to jump in and start making UI tweaks. I have all the major flows built out (I think). Let me know if you want to jump on a call so I can walk you through.

**Comment by conrad-vanl** [comment]
Going to maintain list of things I think we should fix/tweak that I'm not working on yet:

- [ ] Tweak language used in one time SMS and one time Email code. Also, this email went to spam. How to fix?
- [ ] "We just sent you a code. Enter it below when it comes." should really be specific to the mechanism. This copy is fine for text/sms code, but I think it should read "Check your email" for email codes. Also reminder to check SPAM if email.

**Comment by conrad-vanl** [comment]
@vinnyjth I pushed up some basic visual tweaks, and I put together a list above of what I think should get prioritized as far as getting this PR to be a mergeable state.

I can't get my eslint working on my machine correctly (VScode is failing at least) so I'm struggling a bit with that (super frustrating), and I'd like to jump into flushing out pre and post-auth onboarding flows.

The OpenID screen still isn't great, but I made it just a tad better and I'd like to think more on how to improve, but don't think that should hold this PR off.

LMK if you need me to jump into any of the list above

**Comment by vinnyjth** [comment]
@conrad-vanl All great feedback! How do you feel about merging it as-is and then moving forward with the tweaks in another PR? I think I can tackle the tweaks, I might reach out for feedback on error state messages. 

Not sure about the spam issue :/ I can look at our Sendgrid account and see if there's additional things we can do.

**Comment by conrad-vanl** [comment]
I think as long as we're jumping right into tweaks that's fine.

**Review by conrad-vanl — APPROVED** [review]

**Comment by vinnyjth** [comment]
@conrad-vanl I'm moving all these tweaks to basecamp.

**Comment by conrad-vanl** [comment]
@vinnyjth I fixed linter issues related to this branch. looks like there's linter/test failures from elsewhere though, I guess related to #2333

**Pull request merged**
