### PR TITLE
fix: Date picker defaults

### PR DESCRIPTION
**Pull request by vinnyjth**
### What does this PR do, or why is it needed?

Better defaults for the DatePicker. 

It now doesn't allow you to pick a date less than 16 years in the past, but can easily be overriden via `withTheme`. It also defaults to 18 years in the past, so you have some wiggle room for picking your day and month before your year on iOS. 

### How do I test this PR?

Checkout out the `DateInput` stories on iOS. 

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
seems storybook is crashing when trying to test
Kapture 2020-09-28 at 12 13 18

**Comment by vinnyjth** [comment]
Yah, I can't reproduce. Can you open up the native logs and see if you can find where it's crashing? Also check to see if it's crashing in master.

**Comment by redreceipt** [comment]
Screen Shot 2020-09-28 at 12 35 09 PM

**Comment by redreceipt** [comment]
yea master is doing the same thing for me, not sure what happened...

**Comment by redreceipt** [comment]
ok so @vinnyjth getting warmer, tried to test in app, got this. 
Screen Shot 2020-09-29 at 10 56 45 AM

**Comment by vinnyjth** [comment]
@redreceipt Do you get that on master as well?

**Comment by vinnyjth** [comment]
@redreceipt I'm not sure why I'm not getting the error, but this is the exact error you are getting: 
https://github.com/react-native-datetimepicker/datetimepicker/issues/247

We should probably update to 3.0.1 to grab that bugfix.

**Comment by redreceipt** [comment]
Does that mean this needs to be a breaking change?

**Comment by vinnyjth** [comment]
@redreceipt I think we can technically avoid it if we are specific with our `peerDependencies`.  Change the "*" to `3.0.1`

**Comment by redreceipt** [comment]
so explain to me how that works, if we do:

```
ui-kit
-----

peerdeps:
  datepicker: 3.0.1
```

then yarn will automatically use datepicker 3.0.1 under the covers? should be able to test that before merging.

**Comment by vinnyjth** [comment]
@redreceipt I believe it will mean that `yarn` will yell at you and tell you you need to change your local version in your package.json to `3.0.1`. Whenever you `yarn` you can see a list of incompatible peerDeps right now in our current project :) 

Either way, this PR is technically not breaking, seeing as the issue is in master. If we get this in the release, we can solve this package issue in a future.

**Comment by redreceipt** [comment]
True, I’ll go ahead and just bump the version in templates and ui-kit.

**Comment by redreceipt** [comment]
actually if you'll make the version bump and peerdeps apart of this PR, i'll do one for templates and then test the fix.

**Comment by vinnyjth** [comment]
@redreceipt  Done

**Comment by redreceipt** [comment]
no luck 
Screen Shot 2020-09-30 at 9 26 23 AM

i'll start the release, we'll save this one for later

**Comment by redreceipt** [comment]
sike, I tested the wrong thing, it works!
Screen Shot 2020-09-30 at 9 28 27 AM

**Comment by redreceipt** [comment]
although the UI is a little goofy/confusing...

**Comment by vinnyjth** [comment]
@redreceipt So weird!! 

image

**Comment by vinnyjth** [comment]
AHA! 
image

**Review by redreceipt — APPROVED** [review]

**Pull request merged**
