### PR TITLE
chore: move onboarding to core

### PR DESCRIPTION
**Pull request by redreceipt**
test with `onboarding` branch in templates

### CODE REVIEW

**Review by vinnyjth — COMMENTED** [review]
What do I do if I want an onboarding screen _not_ to show up? 

How do I swap out the full screen background view? 

I think those are the two biggest things we'll need to solve here to make this mergeable.

**Comment by redreceipt** [comment]
@vinnyjth I can't tell how this `version` prop is being used? https://github.com/ApollosProject/apollos-apps/blob/617625d89861ea366ae3b9411c2b6f88b88e8cf9/packages/apollos-ui-onboarding/src/Onboarding/index.js#L64

**Comment by vinnyjth** [comment]
> @vinnyjth I can't tell how this `version` prop is being used?
> 
> https://github.com/ApollosProject/apollos-apps/blob/617625d89861ea366ae3b9411c2b6f88b88e8cf9/packages/apollos-ui-onboarding/src/Onboarding/index.js#L64

https://github.com/ApollosProject/apollos-apps/blob/617625d89861ea366ae3b9411c2b6f88b88e8cf9/packages/apollos-ui-onboarding/src/OnboardingSwiper/index.js#L79-L82

**Comment by redreceipt** [comment]
oh. so would setting version to 0 disable them?

**Comment by redreceipt** [comment]
ok @vinnyjth take a look at this

**Comment by vinnyjth** [comment]
> oh. so would setting version to 0 disable them?

Setting user's version to a higher number (like 3) would. I don't think that's what we want though. Some of the apps (I think Willow and Grace) omit some of the slides. I think WIllow omits the gender/age and maybe Grace omits campus selection. I think it's reasonable that we make sure that's still possible

**Comment by vinnyjth** [comment]
or maybe we tell everyone that it's not supported out of the box, and they need to copy this component in? I can see that being reasonable for apps moving forward

**Comment by redreceipt** [comment]
I think I came up with a solution on my latest commit

**Comment by vinnyjth** [comment]
Oh nice! apologies, didn't see it the first time around.

**Review by vinnyjth — APPROVED** [review]

**Pull request merged**
