### PR TITLE
chore: Update to react-native-picker/picker

### PR DESCRIPTION
**Pull request by conrad-vanl**
### What does this PR do, or why is it needed?

This upgrades to the new picker component that has been moved outside of react-native core.

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by conrad-vanl** [comment]
@vinnyjth , I can't actually test this PR b/c I can't get storybook to display stories on the next branch, keep getting this error:
Screen Shot 2020-11-25 at 10 00 36 AM

**Comment by conrad-vanl** [comment]
Screen Shot 2020-11-25 at 10 01 50 AM

@vinnyjth I can't actually test this PR b/c I seem to keep getting errors like this one running storybook on `next`

**Comment by vinnyjth** [comment]
@conrad-vanl I think we need to merge in the media player first, in that case.

**Comment by conrad-vanl** [comment]
Alright @vinnyjth this should be ready, tested.

**Review by vinnyjth — APPROVED** [review]

**Pull request merged**
