### PR TITLE
chore: deprecates auth local resolvers

### PR DESCRIPTION
**Pull request by redreceipt**
Apollo has deprecated local resolvers so we should too. This PR also gives us a fancy new `useLogout` hook.

### CODE REVIEW

**Comment by redreceipt** [comment]
@vinnyjth before you get started on auth, I think this one has value. local resolvers are deprecated in apollo client and this lays out how to write the alternative.

**Review by conrad-vanl — COMMENTED** [review]
this looks amazing

**Comment by conrad-vanl** [comment]
Bumping this back up for @tomthornton / @vinnyjth as they dig into auth

**Review by vinnyjth — APPROVED** [review]
Awesome work, I'm pumped to totally ditch the old auth code.

**Review by vinnyjth — COMMENTED** [review]
Actually hold off a sec - I want to test something

**Review by vinnyjth — CHANGES_REQUESTED** [review]
Auth doesn't appear to persist :/

**Comment by redreceipt** [comment]
Shoot. I’m gonna wait for that auth fix in templates to come through and then debug this.

**Comment by redreceipt** [comment]
@vinnyjth I can't reproduce that, what steps did you take?

**Comment by redreceipt** [comment]
yea I'm not seeing that behavior, works for me
Kapture 2021-11-12 at 18 45 08

**Comment by conrad-vanl** [comment]
Due to the scale of this PR, while I fully support the work, I'm also not comfortable approving it 😬 Would like @vinnyjth 's eyes on it. Sorry @redreceipt

**Comment by redreceipt** [comment]
I was proud of this one...but the code is now invalid :(

**Pull request closed without merging**
