### PR TITLE
fix: Personal Details - Save Button

### PR DESCRIPTION
**Pull request by tomthornton**
Same change from VCC

### CODE REVIEW

**Comment by tomthornton** [comment]
@redreceipt ran `yarn test -u`, added the new snapshots. Still getting an error. Not sure what to do here.

**Comment by redreceipt** [comment]
clicking "details" on the test failure above still shows snap errors

Screen Shot 2021-10-29 at 2 11 09 PM

**Comment by vinnyjth** [comment]
@tomthornton is this PR ready for review?

**Comment by tomthornton** [comment]
@vinnyjth I believe so, yes just the codecov check is failing

**Review by redreceipt — APPROVED** [review]

**Pull request merged**
