### PR TITLE
feat: Flag an Activity in a Community

### PR DESCRIPTION
**Pull request by calebpanza**
## ✏️ Description

- Adds the ability to flag content in a community
- hides globally hidden content on load after reaching report limit

## 🔬 To Test
1. Go to community and click three dot menu in upper right to report
2. click report in dialog
3. content should become hidden

## 📸 Screenshots

image
image

## 📝 Checklist

- [ ] I have performed a self-review of my code
- [ ] I have tested my code works in the project (nothing breaks)
- [ ] I have commented my code in hard-to-understand areas
- [ ] New and existing tests and linting pass locally with my changes
- [ ] I have made corresponding changes to the documentation (new envs?)
- [ ] For PR's with design updates/changes, I have consulted with the product designer and made all necessary adjustments in Figma

### CODE REVIEW

**Comment by camrun91** [comment]
@dsilva609 this is looking good. I noticed that when I report something on the feed that it gets this white space at the top of the feed. it seems to grow with each item I report. 
Screenshot 2023-01-26 at 12 54 57 PM

**Comment by camrun91** [comment]
Also does this include removing the flagged content from the individual community screens?

**Comment by dsilva609** [comment]
> Also does this include removing the flagged content from the individual community screens?

I have it where if the user flagged it or if it meets the flag threshold globally, it'll be hidden. That should probably cover it

**Review by camrun91 — APPROVED** [review]
This looks good to me. just need to get the tests passing.

**Pull request merged**
