### PR TITLE
adds pepk to android deploys

### PR DESCRIPTION
**Pull request by redreceipt**
## ✏️ Description

Adds upload private key to android builds

## 🔬 To Test
1. run `scripts/deploy-android.sh`, you'll see an `android/app/apollos.p8` which you can use to enroll in play app signing
2.

## 📸 Screenshots

Screenshot 2023-02-20 at 2 55 13 PM

## 📝 Checklist

- [x] I have performed a self-review of my code
- [x] I have tested my code works in the project (nothing breaks)
- [x] I have commented my code in hard-to-understand areas
- [x] New and existing tests and linting pass locally with my changes
- [x] I have made corresponding changes to the documentation (new envs?)
- [x] For PR's with design updates/changes, I have consulted with the product designer and made all necessary adjustments in Figma

### CODE REVIEW

**Review by vinnyjth — APPROVED** [review]

**Comment by calebpanza** [comment]
@redreceipt will this need to be done for the `android-and-androidtv` script as well?

**Comment by redreceipt** [comment]
at our current state, yes. although. the steps in this PR are a one-time thing so I almost think it should be a separate script to save run-time. also, we need to abstract some of the shared logic between the two scripts similar to how @vinnyjth modularized the setup script.

**Comment by calebpanza** [comment]
Am I safe to still deploy to Bayside for both Android/AndroidTV? Or should I wait until it's expanded upon?

**Comment by vinnyjth** [comment]
@calebpanza you're safe to deploy

**Pull request merged**
