### PR TITLE
chore: next > master

### PR DESCRIPTION
**Pull request by redreceipt**
- chore: brings in cluster (#2319)
- Setup cluster development
- Simplify identiy code and phone parsing
- Always update users phone numbers to fit db format
- Setup deep linking for auth login
- Add row level security to authentication tables
- Fix migration and handle unique constraints
- Update mutaiton
- WIP Scaffolding schema and resolvers for device OTP (TV sign in) flow
- More iteration on Device OTP flow methods
- Remove unneeded method sketch
- merge in some old PRs from master
- chore: Catch up to master (#2326)
- chore: fix linter (#2332)
- chore: fix tests (#2333)
- feat: ui-authentication / (cluster authentication)  (#2295)
- chore: updates bugsnag library to multitenant (#2330)
- fix: Migrations order and improve logging (#2331)
- fix: removes incorrect prayer index (#2335)
- Fix over eager caching (#2343)
- feat: UI authentication polish (#2339)
- Add enum value LINK_CODE migration
- Generating code works as expected, still WIP schema wise
- Move a console.log
- Sketched out  mutation inputs for claimLinkCode
- feat: Better auth errors (#2345)
- Added openid error states
- Fix action table feature resolver
- Rename and extend changes in OTP migration
- Shuffling and sketching PersonInput types/schema
- fix: Form states caused by old formik (#2347)
- Fix bug caused by new formik verions
- Updated migrations for Identity mgmt, scaffolded claim flow but update piece is failing
- fix: cleans up and fixes app tabs (#2350)
- chore: Make required changes to get m1 building (#2351)
- fix: my prayers bug and clean up action algo (#2356)
- Deprecate old auth mutations (#2362)
- chore: Lockdown prod a teensy bit more (#2364)
- Also load correct production config (#2367)
- Schema and model updates to enable new fields
- Lots of logic shuffling to make claiming link codes work
- feat: Added "register with openid " endpoint (#2363)
- fix: resolves action table actions (#2373)
- fix: properly adds feature action IDs (#2375)
- feat: Connect identity (#2374)
- feat: adds external links to feature actions (#2380)
- feat: adds campus tags to content feeds (#2383)
- feat: New Landing Swiper (#2338)
- Fix snaps (#2390)
- feat: Add Algolia Index Name Option to Config (#2389)
- chore: Ignore VSCODE configuration
- chore: default prayer lists to no-card (#2386)
- Fiddling with Sequelize relationships in models as per Vincent feedback
- feat: Setup content without tags to include everyone (#2388)
- Decouple user creation across the board for request/claim.
- Consolidate auth token generation to new Authentication.createAuthenticatedPerson method
- Clean up logging and consolidate two methods
- Quick code comment tweak
- Few more code comment and log cleanup tweaks
- feat: Add totalCount to Search (#2395)
- Fix OTP unit tests and semantics in datasource
- Fix broken OpenID mock so tests pass again
- OTP.generateLinkCode fully covered
- Coverage for getLinkCodeByCode
- Coverage for claimLinkCode
- Initial Authentication datasource tests
- Rename `code` to `otp` on mutation schema
- Fix failing unit test, DOH
- Missed another otp/code rename spot
- chore: Organize migrations better (#2396)
- Quick patch for migration patcher
- Remove a console log
- Fix child and siblings pulling inactive items (#2406)
- fix: Allow datasources to pass sources array (#2407)
- feat: Better persona feed (#2409)
- conflicts
- fix: global config was overriding church config (#2397)
- feat: Sort newest items with tags first (#2412)
- feat: Priority (#2413)
- feat: V2 of ui-authentication Flow (#2393)
- chore: remove packages
- fix lint
- remove cluster setup
- snaps
- chore: remove old auth pkg (#2423)
- chore!: test breaking change commit
- v3.0.0

### CODE REVIEW

**Comment by vinnyjth** [comment]
@redreceipt This should _not_ be squashed, correct?

**Comment by redreceipt** [comment]
correct. i've set it to auto-non-squash

**Comment by vinnyjth** [comment]
@redreceipt. Awesome - I couldn't see that from here :)

**Review by vinnyjth — APPROVED** [review]

**Comment by redreceipt** [comment]
any harm in turning off linear history requirement? I don't know what that means or understand the implications

**Comment by vinnyjth** [comment]
@redreceipt you can turn it off temporarily. Linear history requires the git history to be orderly/linear in respect to the order PRs were merged, this merge is non-linear by definition since it will be woven into the history of the master branch.

**Pull request merged**
