### PR TITLE
fix: turn off liked content counter for now

### PR DESCRIPTION
**Pull request by nlewis84**
This PR turns off the liked content counter. The query is busted right now, always returning 0. I have spent several hours working on it, as have @calebpanza and @camrun91. I think that puts this in the Low Impact, High Effort category, so we should just turn it off for now. I decided to leave the query and just comment out the accessory text so that we can reenable it quickly, down the road.

|Before|After|
|---|---|
|Simulator Screen Shot - iPhone 13 - 2022-08-10 at 09 17 48|Simulator Screen Shot - iPhone 13 - 2022-08-10 at 09 17 42|

### CODE REVIEW

**Review by vinnyjth — APPROVED** [review]

**Comment by redreceipt** [comment]
i think i may have just fixed this. didn't know it was a long standing issue. cluster PR coming shortly and then i'll need to retest the front end

**Comment by redreceipt** [comment]
https://github.com/ApollosProject/apollos-cluster/pull/269

**Comment by vinnyjth** [comment]
@nlewis84 thanks for your hard work here. @redreceipt has fixed this in the cluster, so I'm going to go ahead and close this

**Comment by nlewis84** [comment]
@vinnyjth @redreceipt Are we sure on that fix? I just checked on City First and Celebration and seeing weird stuff.

|Celebration|City First|
|---|---|
|https://user-images.githubusercontent.com/72768221/184004741-a617eacd-6d6b-44c5-8850-9f062a926532.MP4|https://user-images.githubusercontent.com/72768221/184004760-729eb9c4-2c03-42ec-b4b8-c644e5b32116.MP4|

**Comment by vinnyjth** [comment]
@nlewis84 the change hasn't been promoted to production yet. Try again in maybe 5 mins? I'll test also.

**Comment by vinnyjth** [comment]
It's been deployed - worked for me on newspring.

**Comment by redreceipt** [comment]
It’s fixed on the backend. Front end still has cache bugs. On logout you should see it correct. I’m working on those now.

**Comment by nlewis84** [comment]
Gotcha, yeah I see that. Updates correctly on logout. 👍

**Pull request closed without merging**
