### PR TITLE
feat: add title to text and scripture features

### PR DESCRIPTION
**Pull request by redreceipt**
Screen Shot 2021-02-11 at 12 29 54 PM

### CODE REVIEW

**Comment by vinnyjth** [comment]
@redreceipt Are you going to include the UI for these fields in this PR?

**Comment by redreceipt** [comment]
working on that now, just sent this one to confirm this is the right approach. but I can make it apart of this same one.

**Comment by vinnyjth** [comment]
Either is fine, just wanted to confirm. Your schema here looks perfect.

**Comment by redreceipt** [comment]
ok @vinnyjth give this a look

**Review by vinnyjth — APPROVED** [review]
I love that you were able to hijack the `label`

**Pull request merged**
