### PR TITLE
chore: Add feature priority field for sorting

### PR DESCRIPTION
**Pull request by tomthornton**

### CODE REVIEW

**Comment by vinnyjth** [comment]
@tomthornton Should we include the code that uses this field for sorting in this PR?

**Comment by tomthornton** [comment]
@vinnyjth yeah we can do that. Where is this in the code?

**Comment by vinnyjth** [comment]
https://github.com/ApollosProject/apollos-apps/blob/master/packages/apollos-data-connector-postgres/src/content-items/dataSource.js#L103

**Comment by tomthornton** [comment]
Sorted by ascending. I keep forgetting that `getFeatures` is a sequelize function and not one we created. That's where I was confused.

**Comment by vinnyjth** [comment]
@tomthornton Looks good Tom! Could you add a test for the sorting? Maybe something that features created in an arbitrary order by a set priority will always sort a specific way? I know the changes are simple, but tests like this will help prevent unintentional changes moving forward.

**Comment by tomthornton** [comment]
@vinnyjth added tests

**Review by vinnyjth — APPROVED** [review]
Looking great, thanks @tomthornton!

**Pull request merged**
