### PR TITLE
fix(routing): add back button for no content

### PR DESCRIPTION
**Pull request by dsilva609**
## ✏️ Description
- adds a back button to content that doesn't have valid media
- fixes routing issues for screens without media

## 🔬 To Test
1. Go to a content item that has no valid video media
2. You should see a button that will take you back to the previous screen

## 📸 Screenshots

image

## 📝 Checklist

- [ ] I have performed a self-review of my code
- [ ] I have tested my code works in the project (nothing breaks)
- [ ] I have commented my code in hard-to-understand areas
- [ ] New and existing tests and linting pass locally with my changes
- [ ] I have made corresponding changes to the documentation (new envs?)
- [ ] For PR's with design updates/changes, I have consulted with the product designer and made all necessary adjustments in Figma

### CODE REVIEW

**Review by calebpanza — CHANGES_REQUESTED** [review]
While the primary button might be a bit overkill, can we update this to use it for the time being just for consistency. I'll make sure we get some designer eyes on this to make it less of an eye sore.

**Comment by vinnyjth** [comment]
This PR is definitely a great use for usability, but should we go a step further and prevent navigation to items that don't have media as well?

**Comment by calebpanza** [comment]
@vinnyjth I think that's a larger refactor that we absolutely should consider during next cycle when we're doing cleanup

**Comment by calebpanza** [comment]
There's a product workflow that I don't want to entirely kill. Is there any chance that a church will want to have an item on TV available that doesn't actually have a video? I'm not sure, yet.

**Pull request merged**
