### PR TITLE
feat: Postgres interaction table

### PR DESCRIPTION
**Pull request by vinnyjth**
Adds an `interaction` table / data source. 

Best way to test is to clone the PR and run `BRANCH=interactions yarn api`, then boot the app and click around a few content items. You should see interactions start to fill up in the interaction table.

### CODE REVIEW

**Comment by vinnyjth** [comment]
This should be ready for review, I am double checking everything now in my sim.

**Comment by vinnyjth** [comment]
image

**Comment by tomthornton** [comment]
@vinnyjth awesome! I'm currently only getting "COMPLETE" interactions when I view a content item. That's what you had in the screenshot so I'm assuming everything is working?

**Comment by vinnyjth** [comment]
Yep! You'll only get the `SERIES_STARTED` when visiting a a child item of a parent.

**Review by tomthornton — APPROVED** [review]
Looks great! Nice work.

**Pull request merged**
