### PR TITLE
Updates m1 script fix

### PR DESCRIPTION
**Pull request by tomthornton**
Apparently it's reading my architecture as x86_64 instead of arm64 now.

### CODE REVIEW

**Comment by vinnyjth** [comment]
Hmmm - are you using rosetta? 

`x86_64` is my current arch. 

image

**Comment by tomthornton** [comment]
Yes. That's probably why.

**Comment by vinnyjth** [comment]
Maybe we need something like this
```
#!/bin/zsh
 
arch_name="$(uname -m)"
 
if [ "${arch_name}" = "x86_64" ]; then
    if [ "$(sysctl -in sysctl.proc_translated)" = "1" ]; then
        echo "Running on Rosetta 2"
    else
        echo "Running on native Intel"
    fi 
elif [ "${arch_name}" = "arm64" ]; then
    echo "Running on ARM"
else
    echo "Unknown architecture: ${arch_name}"
fi
```
https://cutecoder.org/software/detecting-apple-silicon-shell-script/

**Comment by rkdavidson** [comment]
I forget what exactly I did to work around this, but IIRC it was just a matter of `brew install`ing the openssl package and double checking my shell's `PATH` stuff.

@tomthornton and @vinnyjth , think this PR is still necessary?

I've had other M1 issues like needing to open Xcode in Rosetta to get `apollos-apps` to run, etc.
So I'm sure there's some work to do, but this specific PR may not be necessary.

**Comment by redreceipt** [comment]
@tom we still need this PR?

**Comment by redreceipt** [comment]
@tomthornton we still need this PR?

**Comment by tomthornton** [comment]
> @tomthornton we still need this PR?

Yeah I need to make a change to it though. I will at some point today.

**Comment by redreceipt** [comment]
@tomthornton are you still having trouble on the M1

**Comment by tomthornton** [comment]
@redreceipt nope, no more problems.

**Pull request closed without merging**
