### PR TITLE
Adds Rookout Debug Information

### PR DESCRIPTION
**Pull request by redreceipt**
### What does this PR do, or why is it needed?

Rookout needs sourcemaps to convert src to lib. And also needs a config file to tell rookout that this repo will be used as an npm dependency.

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by conrad-vanl** [comment]
I'm fine with adding the `sourcemaps`. @vinnyjth should we just do that on all packages?

As far as adding the `rookout` specific package. I'm not against doing that for this case, but fundamentally I don't want to add a bunch of service-specific configuration to each pacakge. Is there not a way you could do this on your end? Maybe a `postinstall` script that copied that file into the `node_modules` file directory?

**Comment by redreceipt** [comment]
> Maybe a `postinstall` script that copied that file into the `node_modules` file directory?

I understand. I could do the `postinstall`. May not even be necessary. They said, "it would help" so I'll try without first.

**Comment by conrad-vanl** [comment]
I'll approve this, but assigning it to @vincent as it'll need an NPM release for it to be helpful for @redreceipt

**Comment by redreceipt** [comment]
I can use canary. 

the `postinstall` won't work but there's another way, working on that now

**Comment by vinnyjth** [comment]
If you're good with a `canary` then I'm going to merge this :) `postinstall` should be what you need? If you run into trouble with your solution send me the deets and we can figure something out.

**Pull request merged**
