### PR TITLE
chore: easy app development

### PR DESCRIPTION
**Pull request by redreceipt**
let's us spin up a template app with no linking headaches

### CODE REVIEW

**Comment by redreceipt** [comment]
@vinnyjth if you want a fun little challenge, it started this similar to your API script, would be awesome. Currently, it's getting hung on the splash screen so I put it down. But i know you had to do some other stuff to get storybook working?

**Comment by vinnyjth** [comment]
@redreceipt you'll likely need to add this :) https://github.com/ApollosProject/apollos-apps/blob/master/ApollosStorybook/metro.config.js

**Comment by redreceipt** [comment]
is that different than the symlink config we already have in the templates repo?

**Comment by redreceipt** [comment]
so strange. by adding "index" to file imports, even works when changing it back

https://www.dropbox.com/s/80wi52n1ptrk0wo/Kapture%202021-05-17%20at%2016.03.17.gif?dl=0

**Comment by redreceipt** [comment]
maybe fixed by #1942

**Review by vinnyjth — APPROVED** [review]

**Comment by redreceipt** [comment]
the only thing that would make this amazing is if I could figure out how to get it all in one command

**Comment by redreceipt** [comment]
or figure out why metro isn't auto-opening like it does for storybook

**Comment by vinnyjth** [comment]
Yah - we can get there :) I like how we have walked through this iteratively so we are building the right tools

**Pull request merged**
