### PR TITLE
feat: 100% Campus postgres

### PR DESCRIPTION
**Pull request by vinnyjth**
You'll want to run with `BRANCH=campus-postgres yarn api`. 

You'll also want to run migrations `yarn api migrator up`

Here's a set of queries you can run in order to test. **Note. You'll have to flip the campuses to active by hand in the DB**
```
query campuses {
  campuses(location:{latitude:45.52252, longitude:-122.67325 }) {
    id
    distanceFromLocation
    name
    state
    street1
    street2
    city
    postalCode
    latitude
    longitude
    image {
      uri
    }
  }
}

query mycampus {
  currentUser {
    profile {
      campus {
        id
        name
        city
        state
      }
    }
  }
}

mutation setCampus {
  updateUserCampus(campusId:"Campus:d8413f08-b5f2-4a3b-9791-c736297bff48") {
    id
  }
}
```

Images won't show up until I finish the shovel work. That's fine for merging this, and I'll work to have images / active done in the shovel before this goes live in a full release.

### CODE REVIEW

**Comment by vinnyjth** [comment]
image

**Comment by tomthornton** [comment]
@vinnyjth code looks great! After running `BRANCH=campus-postgres yarn api` and `yarn api migrator up` I get the error `Error: campus.belongsTo called with something that's not a subclass of Sequelize.Model`. Trying to figure out what would cause this, any ideas?

**Comment by vinnyjth** [comment]
Do you have `DATABASE_CONTENT=true` set in your .env? Sorry, should have mentioned that it in the setup docs.

**Comment by tomthornton** [comment]
That worked!

**Comment by tomthornton** [comment]
@vinnyjth getting three type errors with the first query
`TypeError: Cannot read property 'latitude' of undefined`
`TypeError: Cannot read property 'longitude' of undefined`
`TypeError: Cannot read property 'image' of undefined`

Screen Shot 2021-09-03 at 1 19 31 PM

Says the error is coming from the resolver

**Comment by vinnyjth** [comment]
@tomthornton I copied over my changes from `ApollosApi` to the template incorrectly :) Go ahead and ` BRANCH=campus-postgres yarn api` again, I've corrected it.

**Comment by tomthornton** [comment]
@vinnyjth still getting the same error :/

**Comment by vinnyjth** [comment]
@tomthornton Try now :)

**Comment by vinnyjth** [comment]
@tomthornton If it's not working after the last patch, let me know and we can jump in and pair on it.

**Comment by tomthornton** [comment]
@vinnyjth it's working now but I'm not getting any campuses returned

**Comment by vinnyjth** [comment]
@tomthornton what does your DB look like? Do you have campuses in your database and have you flipped `active` to `True`?

**Comment by vinnyjth** [comment]
I  just booted from scratch and things appear to be working for me: 
image

I pulled data from prod and here's what my DB looks like
image

**Comment by tomthornton** [comment]
@vinnyjth 

DB looks like this
Screen Shot 2021-09-03 at 2 44 12 PM

Query looks like this
Screen Shot 2021-09-03 at 2 45 13 PM

**Comment by vinnyjth** [comment]
What’s your database_url in your .env? Any server logs?

**Comment by tomthornton** [comment]
@vinnyjth
`DATABASE_URL=postgres://localhost/core_prod` (I've pulled the latest from heroku and changed the campuses)

Running this query from the server doesn't return anything
```
SELECT "id",
       "apollos_id"   AS "apollosId",
       "apollos_type" AS "apollosType",
       "origin_id"    AS "originId",
       "origin_type"  AS "originType",
       "name",
       "street1",
       "street2",
       "city",
       "state",
       "postal_code"  AS "postalCode",
       "latitude",
       "longitude",
       "image_url"    AS "imageUrl",
       "digital",
       "active",
       "created_at"   AS "createdAt",
       "updated_at"   AS "updatedAt",
       "image_id"     AS "imageId"
FROM   "campus" AS "campus"
WHERE  "campus"."active" = true;
```
and neither does

`SELECT * FROM campus WHERE campus.active = true`

I'm looking at all of the campuses and the active is all set to true. This is bizarre.

**Comment by vinnyjth** [comment]
Hmmm - is there any chance that you're somehow pointed at a different database? If you log `process.env.DATABASE_URL` somewhere in code does it match what you would expect?

**Review by tomthornton — APPROVED** [review]

**Pull request merged**
