### PR TITLE
chore: deprecate ContentSingle

### PR DESCRIPTION
**Pull request by redreceipt**
Moving to `NodeSingle`

### CODE REVIEW

**Comment by vinnyjth** [comment]
@redreceipt My bad, I misread your question. `ContentSingle` is still being used actively (and should still be used). It includes things like the MediaPlayer that aren't included in `NodeSingle`. I thought you were talking about `ContentChannelItem` (which is deprecated, and I think even deleted) 

Before we merge this PR (which I think is a great goal) we need to consolidate NodeSingle and ContentSingle


https://github.com/ApollosProject/apollos-templates/blob/5f9848476fbaf84a64f8b2735c692b694da15fd2/apolloschurchapp/src/node-single/NodeSingle.js#L14
https://github.com/ApollosProject/apollos-templates/blob/5f9848476fbaf84a64f8b2735c692b694da15fd2/apolloschurchapp/src/content-single/ContentSingle.js#L20

**Comment by redreceipt** [comment]
@vinnyjth those files are client and can be consolidated after this. Are there features in the apps repo where the two components don't match? This PR doesn't delete anything, just throws warnings. So the client shouldn't break.

**Comment by vinnyjth** [comment]
> This PR doesn't delete anything, just throws warnings. So the client shouldn't break.

Feels weird to throw warnings for something that we haven't correct on the client / templates. "Hey you should be doing this, but this isn't up to feature parity with current approach yet".  Given how similar NodeSingle and ContentSingle are, I'm wondering if we should actually ditch `NodeSingle` and just have ContentSingle in the template. Since it looks like ContentSingle is just NodeSingle + theme mixin, analytics, and media player support.

**Comment by redreceipt** [comment]
so you're suggesting ditching `NodeSingle` completely? Deprecating here as well?

**Comment by vinnyjth** [comment]
> so you're suggesting ditching `NodeSingle` completely? Deprecating here as well?

yah, instead of ditching ContentSingle. Given that we actually use ContentSingle, is NodeSingle is just a less built out version of ContentSingle. In theory anything that you need to render with NodeSingle you can instead render with ContentSingle, but the inverse is not true.

**Comment by redreceipt** [comment]
it was created for the `OPEN_NODE` feature action I believe which is more general than `READ_CONTENT`

**Comment by vinnyjth** [comment]
> it was created for the `OPEN_NODE` feature action I believe which is more general than `READ_CONTENT`

Yah that's true, but that was before `ContentNode` when the only other option was `ContentItemSingle`

**Comment by redreceipt** [comment]
Ok, I'll play around with that idea. The reason I have to start in this repo and not templates is that I have to ensure nothing is trying to navigate there before removing it from templates.

**Comment by vinnyjth** [comment]
That's fair! And I'm sorry for the confusion I caused this morning, I should have ready your slack message closer 😬

**Comment by redreceipt** [comment]
easily misunderstood, we have like 100 components with "Content" and "Node" in them. I'm just trying to make that better :)

**Comment by vinnyjth** [comment]
amen! so many nodes and contents and features 🤯

**Pull request closed without merging**
