### PR TITLE
feat: Multiple videos support

### PR DESCRIPTION
**Pull request by tomthornton**

### CODE REVIEW

**Comment by vinnyjth** [comment]
@tomthornton This PR looks good! Could you post a screenshot or two of it in action and then fix the linter so we can review this?

**Comment by tomthornton** [comment]
@vinnyjth Yep! I will first thing tomorrow. I might need a TypeScript ninja to help me fix the errors from the TS compiler but other than that it works pretty well.

**Comment by tomthornton** [comment]
https://user-images.githubusercontent.com/40962668/145070743-ca2279a4-1865-4d69-8342-e23fc722d532.mp4

**Comment by vinnyjth** [comment]
Looking great! Nice work @tomthornton

**Pull request merged**
