### PR TITLE
fix: additionalFeatures back to tabfeedconnected

### PR DESCRIPTION
**Pull request by camrun91**
This should be all that is needed to add additional features back to the tabfeed

### CODE REVIEW

**Comment by redreceipt** [comment]
have you confirmed this works on your end?

**Comment by camrun91** [comment]
@redreceipt Yes I made these changes in the node modules on my personal machine then replicated them in this repo.

**Review by redreceipt — APPROVED** [review]

**Comment by camrun91** [comment]
@redreceipt is there a canary version that I can pull in that has this in it?

**Comment by redreceipt** [comment]
should be now, `yarn add @apollosproject/ui-connected@canary`

**Pull request merged**
