### PR TITLE
Universal & App Links

### PR DESCRIPTION
**Pull request by cdanwards**
### What does this PR do, or why is it needed?

This is a PR based on how we implemented these links in the NewSpring App.
I've written documentation on the doc site on how to add the native code that accompanies this.

I wasn't sure of how to approach this because the prototype app doesn't really have a corresponding site.

Also, there's probably a better way to do this.

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
@vinnyjth could we begin a conversation about merging this into core? it's something every partner church will probably want and in core, we could write it to accept `https://apollosapp.io/<SLUG>` to demo the functionality

**Comment by redreceipt** [comment]
I know a lot of it is similar to what you did with notifications so there's probably a lot of overlap we could account for

**Comment by vinnyjth** [comment]
@redreceipt Totally. Let's wait until we are done with QA though.

**Comment by conrad-vanl** [comment]
I'm tempted to close this one until it starts coming up in other partner apps. While I think this is a great solution with how NewSpring is using univeral links, I'm not convinced it's a solution that will work equally among other apps.

**Pull request closed without merging**
