### PR TITLE
use church slug as deep link host

### PR DESCRIPTION
**Pull request by redreceipt**
removes the need for an extra variable in the DB

### CODE REVIEW

**Review by vinnyjth — COMMENTED** [review]
Are there currently any live apps that have a deep link host that is different from the church slug?

**Comment by redreceipt** [comment]
Probably. The consequences would just be old notification links wouldn't work, right?

**Comment by vinnyjth** [comment]
Correct - and OpenID login wouldn't work for their users (might not be any overlap here though)

Also one or two apps hardcode deep links. Also can't confirm any overlap with digging in.

I think we backed off on this consolidation earlier this year. Might be worth going back to that PR and peeking at our specific reasoning back then.

**Comment by redreceipt** [comment]
> Correct - and OpenID login wouldn't work for their users (might not be any overlap here though)

I didn't think this was a problem since it's the app itself generating the callback

> Also one or two apps hardcode deep links. Also can't confirm any overlap with digging in.

Which ones? I didn't think it could be custom at this point.

> I think we backed off on this consolidation earlier this year. Might be worth going back to that PR and peeking at our specific reasoning back then.

I'll see if I can track it down.

**Comment by redreceipt** [comment]
@vinnyjth I'm the one who introduced it on 8/18 but I don't know why :( https://github.com/ApollosProject/apollos-apps/pull/2642

**Comment by camrun91** [comment]
@vinnyjth and @redreceipt aren't all the links being created server side now? for some reason I thought they were or some of them were.

**Comment by vinnyjth** [comment]
Correct!So old apps receiving newly generated links won’t be able to handle the new linksOn Nov 11, 2022, at 11:08 AM, Cameron Llewellyn ***@***.***> wrote:﻿
@vinnyjth and @redreceipt aren't all the links being created server side now? for some reason I thought they were or some of them were.

**Comment by redreceipt** [comment]
It could use the config variable if present to support apps still using it.

**Comment by redreceipt** [comment]
A better way to do it might be to embed the callback URL in the mutation so there aren't two sources of truth.

**Comment by vinnyjth** [comment]
I really like the idea of using the config variable optionally. It doesn’t add much bloat and we don’t have to expose UI for setting it moving forwardSent from my iPhoneOn Nov 11, 2022, at 11:46 AM, Michael Neeley ***@***.***> wrote:﻿
A better way to do it might be to embed the callback URL in the mutation so there aren't two sources of truth.

**Comment by redreceipt** [comment]
I can do that

**Pull request closed without merging**
