### PR TITLE
feat: Hide unnecessary components 

### PR DESCRIPTION
**Pull request by jimmyhogoboom**
### What does this PR do, or why is it needed?

Checks the new TYPEMAP config value to determine if Up Next button, Parent feed, or Child feed should be displayed on a node. 

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by jimmyhogoboom** [comment]
@vinnyjth I think this is what we're going for, but I'm not sure how to go about testing. Everything I can see in the app and find in Rock seems to be a WeekendContentItem, which has all three features enabled. I think we'd want to see what an item looks like if it doesn't.

**Comment by vinnyjth** [comment]
@jimmyhogoboom You're so close here, the goal is to hide the loading states of each of the components, rather than the components themselves. Your strategy looks spot on besides that 👍

**Comment by jimmyhogoboom** [comment]
@vinnyjth what would we gain from having the component exist on a node where it wouldn't be used? I might not understand exactly what's happening here

**Comment by jimmyhogoboom** [comment]
@vinnyjth Ok I think I've got it! Not entirely sure about the UpNext button though. Hopefully I got it right?

**Comment by vinnyjth** [comment]
@jimmyhogoboom This looks really good at a glance! I think your `UpNext` button is actually _more_ correct than the other two components, we might want to go ahead and `return null` early there as well. 

One thought - can you move the `loadingEnabled` prop to a variable inside each of the components? It will help those components be more self contained, although you'll have to duplicate or somehow modularize the `nodeImplementsType` function. It's great when these components will work given only a `nodeId`.

**Review by vinnyjth — COMMENTED** [review]
@jimmyhogoboom this PR is FANTASTIC! I love the elegance of the `nodeImplementsType` function.

I'm going to test real quick in the sim, and then we can approve this.

**Comment by jimmyhogoboom** [comment]
@vinnyjth woah, thanks man! Do you know what the deal is with the tests, though? Can we ignore that?

**Comment by vinnyjth** [comment]
@jimmyhogoboom It looks like we'll need to add the Typemap into the testing environment. I'll give that a quick shot when I have the PR pulled down :)

**Review by vinnyjth — APPROVED** [review]

**Comment by jimmyhogoboom** [comment]
Now a lint error??

**Comment by vinnyjth** [comment]
@jimmyhogoboom Beat me to the linter fix :)

**Pull request merged**
