### PR TITLE
fix: turns off automerging new people

### PR DESCRIPTION
**Pull request by redreceipt**

### CODE REVIEW

**Comment by conrad-vanl** [comment]
@redreceipt code looks good, what did you do to test this?

**Comment by redreceipt** [comment]
testing now, I'll make this a draft until then

**Comment by redreceipt** [comment]
FYI, not an issue for v1

Screen Shot 2021-06-11 at 1 55 23 PM

**Comment by redreceipt** [comment]
Screen Shot 2021-06-11 at 2 34 30 PM

**Comment by redreceipt** [comment]
ok, @conrad-vanl @vinnyjth this one is ready to look over. Note the test changes that were necessary.

**Review by vinnyjth — APPROVED** [review]
Should we also add a flag to enable/disable this behavior?

**Pull request merged**
