### PR TITLE
Fix issue where re-renders aren't picked up in StretchyView

### PR DESCRIPTION
**Pull request by conrad-vanl**
### What does this PR do, or why is it needed?

If you've ever noticed a bug in our apps where pulling down on a content-item causes the cover image to flash to gray - this fixes it!

This issue is caused by re-renders to the children you pass to `<Stretchy>` are not picked up. I hacked together a "clever" solution using `useEffect` and a deep-comparison on `children` to mitigate. It's....not super clean but it is succinct and I think fairly stable.

### What design trade-offs/decisions were made?

Before:

ezgif com-optimize (1)

After:

ezgif com-optimize (2)

### How do I test this PR?

Check out the story! Press the button.

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by conrad-vanl** [comment]
@asleepingpanda merry christmas 😘

**Comment by asleepingpanda** [comment]
I love it! Can't wait to have it back in our app!!

**Comment by asleepingpanda** [comment]
For what it's worth, there are a couple of packages that exist that I found that do this same behavior if we didn't want to have to maintain this code. Only trade-off is that those packages seem to limit the "stretchiness" to just a photo.

**Comment by conrad-vanl** [comment]
Yeah, well the other packages kind of sucked and ours is better 😅

**Pull request merged**
