### PR TITLE
cleans up xcode proj and fixes tvos setup scripts

### PR DESCRIPTION
**Pull request by redreceipt**
## ✏️ Description

1. Cleans up unnecessary iOS targets in the Xcode proj
2. Renames reference in Obj-C file that causes app crash on startup

## 🔬 To Test

- Boot TV template
- run setup-tv script and boot TV inside "deploys" directory

## 📸 Screenshots

N/A

## ⚠️ To-do Before Merge

N/A

## 📝 Checklist

- [x] I have performed a self-review of my code
- [x] I have tested my code works in the project (nothing breaks)
- [x] I have commented my code in hard-to-understand areas
- [x] New and existing tests and linting pass locally with my changes
- [x] I have made corresponding changes to the documentation (new envs?)
- [x] For PR's with design updates/changes, I have consulted with the product designer and made all necessary adjustments in Figma

### CODE REVIEW

**Comment by vinnyjth** [comment]
Is there any good way to test this?

**Comment by redreceipt** [comment]
You could boot the TV template and then run the setup script and boot it inside the deploys directory too

**Comment by calebpanza** [comment]
@redreceipt when I open up the Workspace file for the tv project, Xcode doesn't load any files:
CleanShot 2022-12-06 at 12 11 54

**Comment by calebpanza** [comment]
Opening up the Xcode _project_ file loads up ok, but the workspace does not
CleanShot 2022-12-06 at 12 13 06

**Comment by redreceipt** [comment]
the pods are red on your screenshot, try running pod install first?

**Comment by calebpanza** [comment]
I'm seeing the following warnings when running the setup script. Is this to be expected?


```bash
mv: no such file or directory: /Users/calebpanza/Developer/ApollosProject/apollos-apps/deploys/tv/ios/ApollosChurch.xcodeproj/xcshareddata/xcschemes/tvappnative.xcscheme

...

mv: no such file or directory: /Users/calebpanza/Developer/ApollosProject/apollos-apps/deploys/tv/ios/ApollosChurch/tvappnative.entitlements

...

mv: no such file or directory: /Users/calebpanza/Developer/ApollosProject/apollos-apps/deploys/tv/ios/tvappnative-Bridging-Header.h
```

**Comment by calebpanza** [comment]
> the pods are red on your screenshot, try running pod install first?

That seems to have done it. I guess for this project, neither the project files nor the pods will show up until the `pods` command it run, so that's looking good now!

The project ran successfully inside of that `deploys` directory, too. So as long as we aren't concerned bout those warnings above, I can mark this as approved

**Comment by redreceipt** [comment]
do you remember where in running the setup script you saw those warnings?

**Comment by redreceipt** [comment]
making this a draft to investigate

**Comment by redreceipt** [comment]
@calebpanza thanks for the thorough review. it alerted me to some other stuff I needed to clean up before merge. Unrelated, I think the warnings you're referring to are fine. That's just the renaming pkg can't find certain iOS files. I think that warning has always been there.

Screenshot 2022-12-06 at 2 16 11 PM

**Comment by calebpanza** [comment]
Sounds great! I'll give it another review this evening to confirm the latest changes and we should be good to go!

**Comment by calebpanza** [comment]
Ran the `setup-tv.sh` and was successfully in running the project from the `deploys` folder. The Xcode workspace _does_ open up and displays information _after_ the `pods` command is run, but since that's expected behavior, I think this is good to go!

**Review by calebpanza — APPROVED** [review]

**Pull request merged**
