### PR TITLE
fix: add sharing to text and scripture features

### PR DESCRIPTION
**Pull request by redreceipt**

### CODE REVIEW

**Comment by vinnyjth** [comment]
@redreceipt Why not have Text/Scripture feature `implement ShareableNode`

**Comment by redreceipt** [comment]
> @redreceipt Why not have Text/Scripture feature `implement ShareableNode`

It is, I just threw it in the function right above that extends content items

**Comment by redreceipt** [comment]
oh sike wrong PR

**Comment by vinnyjth** [comment]
> oh sike wrong PR

😂 been there

**Comment by redreceipt** [comment]
that was the other PR. unfortunately it's not that simple because `SharableNode` uses `SharableContentItem` as its field so it didn't work like I'd hoped.

**Comment by redreceipt** [comment]
which explains the v3 PR I just sent 😂

**Comment by vinnyjth** [comment]
> unfortunately it's not that simple because `SharableNode` uses `SharableContentItem`

Well that's super frustrating. It would all be perfect if ShareableContentItem was just `ShareableContent` or something

**Review by vinnyjth — APPROVED** [review]

**Comment by redreceipt** [comment]
> > unfortunately it's not that simple because `SharableNode` uses `SharableContentItem`
> 
> Well that's super frustrating. It would all be perfect if ShareableContentItem was just `ShareableContent` or something

exactly, pretty much what I did in the breaking change PR

**Pull request merged**
