### PR TITLE
makes deep and universal link config variables optional

### PR DESCRIPTION
**Pull request by redreceipt**

### CODE REVIEW

**Comment by camrun91** [comment]
@redreceipt what is the best way for me to test this?

**Comment by camrun91** [comment]
The code looks good I would love to test first just to make sure.

**Comment by redreceipt** [comment]
thanks for taking a look @camrun91 . this one is actually dependent on https://github.com/ApollosProject/apollos-cluster/pull/368 which @vinnyjth found problems I need to fix first. I'll mark this as a draft until that one is ready.

**Comment by redreceipt** [comment]
timing isn't right here

**Pull request closed without merging**
