### PR TITLE
chore: Version Override

### PR DESCRIPTION
**Pull request by vinnyjth**
CleanShot 2022-08-01 at 14 20 04@2x

Allows us to (optionally) supply an initial version. Will only be used if it's higher than the current app store version (+1) so there's no reason to ever reset/unset it if we forget.

### CODE REVIEW

**Comment by redreceipt** [comment]
I approved blindly, but what's the use case here 😂

**Comment by vinnyjth** [comment]
> I approved blindly, but what's the use case here 😂

For deploying apps that have a larger version in testflight than what they have deployed in the App Store. 

I don't see an obvious way to get the version from TestFlight, so it seems easier to set an initial version :)

**Comment by redreceipt** [comment]
Perhaps a better question, why would the version need to be lower?

**Comment by vinnyjth** [comment]
See latest celebration build for an example: 

https://app.bitrise.io/build/100e20ef-15e4-4d91-8843-f1e8c766de4e

Latest App Version is 5.19, but the latest Test Flight version is 12.0.0

**Comment by vinnyjth** [comment]
> Perhaps a better question, why would the version need to be lower?

I don't think it can be lower :)

**Comment by vinnyjth** [comment]
@redreceipt Lol, fixed a typo in PR description ;)

**Comment by redreceipt** [comment]
Fastlane may have a flag to overwrite the current edit version but I'm not positive

**Comment by redreceipt** [comment]
Regardless, I like us having the ability to set the version anyway so good add

**Pull request merged**
