### PR TITLE
Async Live Content Filter

### PR DESCRIPTION
**Pull request by redreceipt**
### What does this PR do, or why is it needed?

This gives churches the ability to have dynamic live content filters.

@vinnyjth I know this is daunting but I do think it will be beneficial in the long run for folks. I just made this so you could a take a look and make a decision one way or the other. I tried to deprecate all the non-async functions and then on 2.0, we could put the names back. I didn't change the tests (there's a ton) hoping that 2.0 might be sooner than later and because the functionality of the filter didn't change at all.

### What design trade-offs/decisions were made?

Don't think any.

### How do I test this PR?

Boot up the app and make sure everything looks ok.

### What automated tests did you write?

None.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes [tag-issues-here]
- [x] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
@vinnyjth I fixed the tests here if you wanted to give this one a look.

**Comment by vinnyjth** [comment]
I went over this PR this morning @redreceipt. 

I think your approach is a valid one, and under certain conditions I think it would be the right one for Apollos. But at this time, I think it doubles the landscape of the content-item datasource without much immediate gain. I think. if we could omit backwards compatibility, it would be easier to tolerate a change like this and be able to handle that change across the growing number of repos. 

However, I think there are a few universally beneficial changes that would make what you're trying to do in the Newspring app easier to accomplish. For example: 
- https://github.com/ApollosProject/apollos-apps/blob/master/packages/apollos-rock-apollo-data-source/src/index.js#L78 The `.paginate` method doesn't `await` it's cursor, but it could without breaking anything! 
- https://github.com/ApollosProject/apollos-apps/pull/1372/files#diff-b177d4dac4e73f6ec162e470c50adaa9R244 Methods like this (that you've already fixed) can remain fixed. If something might be a async cursor, and you're in an async method, no reason not to await! 

I think if you start from that point, you might be able to get close enough to the point where you can override core methods on your app to accomplish what you need to accomplish. For now, I would rather try and fix the building blocks rather reconfigure the components that those blocks built.

**Comment by redreceipt** [comment]
@vinnyjth I think I understand. So you're saying on the core side, I could make `paginate` await the cursor, leave the `getLiveContentFilter` async function in there, and then on the NewSpring side run all our content queries' cursors through the new filter function? so `userFeed`, `userFeedFeatures`, child and sibling connections, search queries, liked content connections, and any more I can think of. Is that what you're saying?

**Comment by redreceipt** [comment]
actually I wouldn't even need to put the async filter function in core. Only core change needs to be `paginate` to await its cursor. Right?

**Comment by redreceipt** [comment]
so really i'm just overwriting every resolver instead of every data source function right?

**Pull request closed without merging**
