### PR TITLE
feat: Add audio play button

### PR DESCRIPTION
**Pull request by christinamegura**
This PR adds audio support so that the audio play button will show if there is no video present.

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by conrad-vanl** [comment]
This pull request is being closed to clear out "backlog" post cycle ending. You can push to have it reprioritized in a future cycle or re-open once changes have been made and it is ready for review.

**Comment by redreceipt** [comment]
@christinamegura where does this one stand?

**Comment by christinamegura** [comment]
I still need to write the test file (then update snaps). It's been a minute...

**Comment by redreceipt** [comment]
sweet, holler if you want another set of eyes or get stuck!

**Pull request closed without merging**
