### PR TITLE
fix: Update prayer algorithm 

### PR DESCRIPTION
**Pull request by christinamegura**
## DESCRIPTION
When there are no prayers requested within 24 hours and all prayers have been prayed for, no prayers would show in the app. 

### What does this PR do, or why is it needed?
This PR updates the prayer algorithm by replacing a hard coded data source method and exposing it as an argument.

This gives churches the flexibility to change the number of days since a prayer has been made to show up in the app. The default is now three days, instead of one.

### How do I test this PR?
On the `dailyPrayerAlgorithm` in `apollos-data-connector-rock/src/action-algorithms` console log the prayer request attributes in your terminal and confirm that the `EnteredDateTime gt datetime` = three days ago. 

For example, today is 2020-11-18 so I need to confirm that `EnteredDateTime gt datetime` = 2020-11-15.
Screen Shot 2020-11-18 at 1 58 53 PM

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by christinamegura** [comment]
@vinnyjth do you think that's good enough for testing this PR?

**Review by vinnyjth — CHANGES_REQUESTED** [review]
@christinamegura Yah, I think the tests here are perfect! 

This PR looks really good! You've accomplished the goal of making sure that users will have a broader body of prayers to choose from. There's one simple tweak I think we can add, to improve this functionality even further from our clients. 

Do you think we could/should change where the `number of days back` comes from? Right now that `3` is hardcoded in the dataSource method, but I think it would be valuable to expose it as an argument to the method so if a church wanted to go back further, or maybe revert to going back only one day, they could.

**Comment by christinamegura** [comment]
@vinnyjth, okay, I'm closer! I still need to pass a unit test. I'll tackle in the AM

**Review by vinnyjth — APPROVED** [review]
Looks great @christinamegura :D As soon as you get tests passing feel free to merge this.

**Pull request merged**
