### PR TITLE
chore: adds tvOS deployments

### PR DESCRIPTION
**Pull request by redreceipt**
Screenshot 2022-10-31 at 9 07 48 PM

### CODE REVIEW

**Comment by redreceipt** [comment]
this is getting hung up with fastlane trying to do release builds. it uses this command which we can use to shortcut debug: `xcodebuild -workspace ios/ApollosChurch.xcworkspace -scheme ApollosChurch-tvOS -destination 'generic/platform=tvOS' archive`

**Review by calebpanza — COMMENTED** [review]
@redreceipt I was able to successfully install the tv app on my Apple TV, although no navigation works. Is that expected at this point?

**Comment by jordanwade** [comment]
@calebpanza do you mean the remote isn't working? That would be strange regression.

**Comment by calebpanza** [comment]
@jordanwade the remote technically works, although I am only able to interact with the Search button. Navigating any direction on the remote does nothing.

It _could_ be that this is just expected atm cause we don't have final content and such. but I just wanted to call it out in case this was working on the simulator in which it's not working on a physical device.

**Comment by redreceipt** [comment]
@calebpanza if that is the case, it's beyond the scope of this PR and should be fixed elsewhere. All this does is get automated deploys working.

**Comment by jordanwade** [comment]
@calebpanza thanks I'll capture that in an F&I TODO

**Review by calebpanza — APPROVED** [review]

**Pull request merged**
