### PR TITLE
correctly fails on invalid version numbers

### PR DESCRIPTION
**Pull request by redreceipt**
## ✏️ Description

Another versioning PR... 🙄

## 🔬 To Test
1.
2.

## 📸 Screenshots

before and after

Screenshot 2023-02-21 at 10 49 37 AM

## 📝 Checklist

- [x] I have performed a self-review of my code
- [x] I have tested my code works in the project (nothing breaks)
- [x] I have commented my code in hard-to-understand areas
- [x] New and existing tests and linting pass locally with my changes
- [x] I have made corresponding changes to the documentation (new envs?)
- [x] For PR's with design updates/changes, I have consulted with the product designer and made all necessary adjustments in Figma

### CODE REVIEW

**Comment by calebpanza** [comment]
Does it also need to on `android-and-androidtv`?

**Comment by vinnyjth** [comment]
Love it - do you think we can move this logic to the `setup` steps? 

I would love to bomb out if a version number is incorrect quickly in the build process.

**Comment by redreceipt** [comment]
That's an interesting thought. Not as it stands I don't think because currently iOS and android version numbers could be different. We wouldn't want iOS to bomb if it's just android that's screwed up. But there is probably a rearrangement we could make to catch certain problems early.

**Comment by vinnyjth** [comment]
Gotcha - maybe we can save that for another PR then. On Bitrise we can only the iOS code on the iOS lane (and vice versa). 

I'll focus on moving the Bitrise config into Github.

**Review by vinnyjth — APPROVED** [review]

**Pull request merged**
