### PR TITLE
feat: Adds User Prayers Feature (API)

### PR DESCRIPTION
**Pull request by redreceipt**
This adds a `UsersPrayers` feature option to the config, returning the prayer list of a specific user

Screen Shot 2021-01-21 at 2 16 34 PM

### CODE REVIEW

**Comment by redreceipt** [comment]
blocked on #1690

**Comment by redreceipt** [comment]
@vinnyjth before you approve this, would it be a better approach to not use a separate feature, but instead just use the `PrayerList` feature for a different component and simply use the data to construct the UI?

**Comment by redreceipt** [comment]
well on second thought, there would be no way to specify which UI component to use from the config unless we had a separate feature type. just seems very redundant to build almost the same thing on the backend to make the front-end look different.

**Comment by redreceipt** [comment]
for clarity, this is what we're building. could easily be done with the existing `PrayerListFeature`

**Review by vinnyjth — APPROVED** [review]

**Pull request merged**
