### PR TITLE
Adds background audio playback

### PR DESCRIPTION
**Pull request by redreceipt**
### What does this PR do, or why is it needed?

Enables background audio playback in iOS

### What design trade-offs/decisions were made?

None.

### How do I test this PR?

Play a video and watch it keep going in the background. Works on a sim.

### What automated tests did you write?

None.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes [tag-issues-here]
- [x] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
@redreceipt Thank you much for this PR. Can you do one favor for me? All of those changes with the <true /> / <false /> tags will cause conflicts in the update tool, can you try and back out those changes? 

Thanks!

**Comment by redreceipt** [comment]
Totally. But it does beg the question, that happened because XCode did it, shouldn't that be the standard? Even If it causes conflicts one time?

**Comment by vinnyjth** [comment]
@redreceipt Xcode seems to behave and format those spaces slightly differently machine to machine. What my Xcode version generates might be slightly different than what my generates. I've worked to match core as closely as possible with the client apps, and then work to change the core files as little as possible.

**Comment by redreceipt** [comment]
done

**Comment by vinnyjth** [comment]
thanks man!

**Pull request merged**
