### PR TITLE
Stop scripture Regex from butchering the word from

### PR DESCRIPTION
**Pull request by vinnyjth**
## ✏️ Description

In the current version of the app, phrases like "Visit our Church from 1-2" are picked up as a scripture reference, Romans 1-2. This fixes that by ensuring that we have a non-word character or space before the scripture reference starts. 

## 🔬 To Test
1. Visit "Item 5" in Apollos Demo
2.

## 📸 Screenshots
Before
CleanShot 2022-11-15 at 13 59 14

After
CleanShot 2022-11-15 at 16 12 24

## 📝 Checklist

- [x] I have performed a self-review of my code
- [x] I have tested my code works in the project (nothing breaks)
- [x] I have commented my code in hard-to-understand areas
- [x] New and existing tests and linting pass locally with my changes
- [x] I have made corresponding changes to the documentation (new envs?)
- [x] For PR's with design updates/changes, I have consulted with the product designer and made all necessary adjustments in Figma

### CODE REVIEW

**Review by calebpanza — COMMENTED** [review]
Did we do any test for weirdly formatted references like `Romans 1-Romans 2`? Might be good to document the "approved" formats in code so we can advise churches if the topic ever comes up.

**Comment by vinnyjth** [comment]
@calebpanza not behind what's already in our test suite. The reference you posted will show up as a reference in the app, "Roman 2"

**Comment by vinnyjth** [comment]
@calebpanza I added a couple more tests this morning.

**Review by calebpanza — APPROVED** [review]
Seems good to me! Thanks for adding those extra cases

**Pull request merged**
