### PR TITLE
Removes Browser Modal View By Default

### PR DESCRIPTION
**Pull request by redreceipt**
## DESCRIPTION

Screen Shot 2019-09-30 at 1 44 51 PM

### What does this PR do, or why is it needed?

The Modal view is unnecessary and doesn't work anyway, removing `modal = true` by default, can circle around later if we want to fix.

### What design trade-offs/decisions were made?

None

### How do I test this PR?

Click the test link in the test panel

### What automated tests did you write?

None

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes [#909]
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
@redreceipt I would prefer to figure out why the ModalView is not working, in this instance :)

**Comment by richarddubay** [comment]
Just my opinion (so take it FWIW), but I don't think the in-app browser should be a modal or have modal behavior. I feel like it should have native in-app browser behavior: comes up with the bar at the top with a button that says "Done" or "Close" (or whatever it is that Android has). The modal "X" and any other modal functionality should be saved for our content.

**Comment by vinnyjth** [comment]
@richarddubay we need to have two modes for the browser. 

1. The one you are describing, I'm calling it a `modal` behavior, I think having the Done or Close button instead of the X would be totally fine here. 

2 The ability to embed an in app browser within another screen, discretely. Imagine a browser that renders a QR code on the profile screen. 

So in essence, we need the ability to have a fullscreen "modal" browser, and an embeddable browser.  Right now we are only doing the latter properly, I think

**Comment by richarddubay** [comment]
@vinnyjth Is the "embeddable browser" something that we had before and is broken with this implementation?

**Comment by redreceipt** [comment]
yea...I'll fix it :)

**Comment by redreceipt** [comment]
ok @vinnyjth here it is

**Comment by richarddubay** [comment]
@vinnyjth Is this something we can discuss getting in pretty soon? Having two ways to close this isn't ideal.

**Comment by vinnyjth** [comment]
Sorry @richarddubay  - didn't realize this was ready for review. These are all changes you can make directly to your app, I would recommend doing that in the meantime while I review and merge this. That way you aren't blocked by me to get these changes.

**Comment by redreceipt** [comment]
@richarddubay I say we just wait. We'll be switching to In-App Browser anyway for all our links, we don't use the web view anymore.

**Comment by richarddubay** [comment]
If we're removing the web view then I'm fine with waiting.

**Comment by conrad-vanl** [comment]
@redreceipt overall I think this looks good. Might have a few questions, but I think we need to resolve conflicts first - which means moving this code into one of our packages and considering what still needs to be done based on anything new we have in core.

**Comment by redreceipt** [comment]
so @conrad-vanl to summarize, to move this forward, I need to move the `user-web-browser` out to a package (probably `ui-connected`) and remove the modal view there?

**Comment by conrad-vanl** [comment]
We have a `RockAuthedWebBrowser` (I think that's what it's called) in one of those packages. There might be another web browser too... I don't recall with 100% certainty. But yeah - you'll haveto move these changes.

Also, I think there was some confusion above on `ModalView` vs `modal` config option on the web browser. Can you explain, perhaps with pictures, the difference between `modal=false` and `modal=true`?

**Comment by redreceipt** [comment]
> Also, I think there was some confusion above on `ModalView` vs `modal` config option on the web browser. Can you explain, perhaps with pictures, the difference between `modal=false` and `modal=true`?

`ModalView` just adds that little "X" but that's the whole point of this PR. It's redundant with also having the back button.

**Comment by conrad-vanl** [comment]
@redreceipt ahhh, I completely agree! I'm good with moving this forward then :)

**Pull request closed without merging**
