### PR TITLE
feat: Pull to refresh on the connect tab

### PR DESCRIPTION
**Pull request by vinnyjth**
### What does this PR do, or why is it needed?

Two things 

- Adds pull to refresh to the connect tab. Uses a similar strategy as the featureFeeds to refetch multiple children components. 
- Moves the connect tab to a `ConnectScreenConnected` component. Gasp. I might be jumping the horse a bit on this one, but I think it's a start in the right direction. Removes a ton of code from templates: https://github.com/ApollosProject/apollos-templates/pull/291

### How do I test this PR?

Clone the companion PR (https://github.com/ApollosProject/apollos-templates/pull/291). Visit the connect tab. Pull to refresh. You should see your API console register the pull and show you a few queries running (I have a gif on my work computer)

### CODE REVIEW

**Comment by redreceipt** [comment]
sweeeet, I'll test this ASAP

**Comment by redreceipt** [comment]
this is all I'm getting, loading state is stuck

Screen Shot 2021-03-17 at 9 28 43 AM

**Comment by vinnyjth** [comment]
> I'm testing with no postgres

ah, then the errors you are seeing make sense. the features that pull to refetch are both driven by postgres

**Comment by redreceipt** [comment]
problem is my name isn't showing up

**Comment by vinnyjth** [comment]
@redreceipt That's also to be expected, until we merge in that feature flag branch. It's trying to pull your profile from postgres.

**Comment by redreceipt** [comment]
gotcha. well I love the code in this one so once that's in so this one doesn't break, I'll approve. it's currently got some conflicts.

**Comment by vinnyjth** [comment]
> well I love the code in this one so once that's in so this one doesn't break

I think you'll see the same broken state in master right now :)

**Pull request merged**
