### PR TITLE
fix: disappearing cancel search button

### PR DESCRIPTION
**Pull request by nlewis84**
Added logic to treat the cancel button the same as the clear search button (if there is text in the input field). If there is no text, it closes the modal.

Before:
https://user-images.githubusercontent.com/72768221/128533019-998d32b2-98b0-4b91-9ff1-1b26f32447ec.mp4

After:
https://user-images.githubusercontent.com/72768221/128533028-3fa8dea6-52f3-4c55-9c34-99659db6c0ad.mp4

### CODE REVIEW

**Comment by redreceipt** [comment]
Why shouldn't the cancel button always close the modal no matter what? that's what it seems like its purpose should be

**Comment by nlewis84** [comment]
Good point

**Comment by redreceipt** [comment]
so now the only change is we're clearing out the text first? i don't understand why that's necessary?

**Comment by nlewis84** [comment]
I'm not sure why, I just know that it works. I'll investigate and get back to you.

**Comment by nlewis84** [comment]
Looks like it has to do with the state of isFocused (lines 55-80)

**Comment by redreceipt** [comment]
that's the bit I feel like we should improve to fix this problem if possible :/ or else we're just pushing our problems around and leaving problematic code in there

**Comment by nlewis84** [comment]
The whole bit about hiding and showing the cancel button and setting focus seems unnecessary.

**Comment by redreceipt** [comment]
I'm always down for removing what's unnecessary. Easy way to fix A LOT of problems and future problems.

**Comment by nlewis84** [comment]
Hmmm okay, I'm spinning my wheels on this. Should I close this since the work will be much different and just open a new PR when I've got something figured out, or just leave it open?

**Comment by redreceipt** [comment]
Up to you. I just don’t feel great approving a seemingly redundant addition that mysteriously fixes problems.

**Pull request closed without merging**
