### PR TITLE
Decrease the cache time for the livestreams query

### PR DESCRIPTION
**Pull request by vinnyjth**
### What does this PR do, or why is it needed?

Didn't realize this was GraphQL's behavior, but it makes sense 🤷‍♂ If a field isn't included in a response, then it's `maxAge` value is not respected for the returned result. 

## Before

Screen Shot 2020-03-16 at 8 20 11 AM
Screen Shot 2020-03-16 at 8 21 12 AM

## After

Screen Shot 2020-03-16 at 8 26 18 AM

### What design trade-offs/decisions were made?

Long term there's a better fix for this PR, but we'll need to be clever about it because it will cause breaking changes. 

1. Setup the `LiveStreams` query so that it _always_ returns content items, even if the `liveStream.isLive` is `false. 
2. Change the client LiveStream provider so that it uses the `true/falseness` of `LiveStream.isLive` rather than the presence of the item in the array. **I'll include that fix in this PR**. 

If we do step 1, without first deploying step 2, old versions of the app will display content as live perpetually. 

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
If I may disagree, I think the max age would suffice here. returning content items even when there's no active live stream is confusing. plus this requires an app update. I thought the API functioned better as is.

**Comment by redreceipt** [comment]
So essentially it makes the `liveStreams` query function as a `mostRecentSermon` query

**Comment by vinnyjth** [comment]
Okay - I buy that @redreceipt. I don't think we need to back out the client changes in this PR though, even if it's not necessary it is more correct.

**Comment by redreceipt** [comment]
> Okay - I buy that @redreceipt. I don't think we need to back out the client changes in this PR though, even if it's not necessary it is more correct.

Agreed.

**Pull request merged**
