### PR TITLE
Skips Onboarding When Unnecessary

### PR DESCRIPTION
**Pull request by redreceipt**
## DESCRIPTION

Screen Shot 2019-08-13 at 4 57 48 PM

### What does this PR do, or why is it needed?

This will keep track of which users have completed onboarding and skip it the next time they log in on the device.

### What design trade-offs/decisions were made?

- Made some changes to some redundant and confusing props in the onboarding connected components.
- Had to add `removeClippedSubviews={false}` to the swiper: https://github.com/leecade/react-native-swiper/issues/416

### How do I test this PR?

Go through onboarding, log out, and log back in.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] Closes [#913]
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
@vinnyjth I think I'm close here, how do you recommend I get the `currentUser` here? `Onboarding` is the first component loaded in the app so there's no parent to run a query and pass in as a prop. And it's not in cache yet at this point.

**Comment by vinnyjth** [comment]
@redreceipt One pattern we have done for this in the past, is have a component that renders as a part of onboarding (but doesn't actually render any UI) that uses an apollo query to fetch current user, and then acts on that response. You could create a function called something like `checkIfOnboardingCompleted` that calls `client.query`. You will need to use an `ApolloConsumer`to get the apollo client to pass in, if you do that.

**Comment by redreceipt** [comment]
so....close, currently I'm triggering the `getUser` query on the button pushes but that means that I have to push the first "Next" button before the query is run, is there a way I can run the query on mount? The kicker is I need the `client` from somewhere.

**Comment by redreceipt** [comment]
i'm gonna make a parent `OnboardingConnected` and pass in the client that way

**Comment by redreceipt** [comment]
This one works but I don't think it's 100% there. The first screen hangs until the `currentUser` comes back and then skips once it's got it. And I had to add `removeClippedSubviews={false}` to the `Swiper` because the first screen was not displaying content until you started to swipe it. Very strange. Documented here: https://github.com/leecade/react-native-swiper/issues/416, not really sure what changed and why this is necessary now. 

Hoping someone will have some great ideas about how to push this one over the edge.

**Comment by redreceipt** [comment]
@conrad-vanl @vinnyjth I've thought a little more about this one. If this goal is that they would still have to go through it when they have a new device (which makes sense so we can capture notifications) then the only thing this is getting us is when multiple people are using the same device. Very small edge case for such a complex solution. I say we kill this.

**Comment by vinnyjth** [comment]
>  If this goal is that they would still have to go through it when they have a new device (which makes sense so we can capture notifications) then the only thing this is getting us is when multiple people are using the same device. Very small edge case for such a complex solution. I say we kill this.

Totally agree. I think we can take the core concepts from this PR and refine it to a situation where once a user completes (or skips 🤷‍♂) onboarding, we don't show it to them or any other user again on the same device.

**Comment by redreceipt** [comment]
I'm a little confused, are we killing this or changing the design? I think what you've described is what this already does but I just don't if it's really getting us that much.

**Comment by vinnyjth** [comment]
@redreceipt This PR keeps track of what stage a user completed in onboarding as well as what user ids have completed onboarding on the device. I think we can ignore both of those constraints and end up with some less but better code.

**Comment by redreceipt** [comment]
What's the high-level goal?

**Comment by vinnyjth** [comment]
A user shouldn't have to go through onboarding every time they login on their own device.

**Comment by redreceipt** [comment]
Are we ok with not asking about permissions again if they skipped it?

**Comment by vinnyjth** [comment]
Yep! But @conrad-vanl can override me if I'm wrong

**Comment by redreceipt** [comment]
That's the piece I'm a little worried about because there's currently no other place in the app to enable those permissions if they skipped them the first time.

**Comment by burkeshartsis** [comment]
Jumping in here to provide some UX guidance as this PR have become pretty stale. If a user goes through onboarding and skips a slide without clicking any of the CTA's that prompt for permission we should provide a way for them to come back and enable them. However, if a user **denies** a permission we loose the opportunity to ever prompt again on iOS and as a result should assume the same on Android.

There are lots of ways we could prompt for permissions. Here are some below:

1. check and prompt in place when a permission is needed. This wouldn't take a lot of work but would require some changes around the app. Code is super straight forward. Check for permission > open modal with the correct onboarding slide 💥This is actually a better UX then having an onboarding at all.
2. Add a link to the setting page to "Setup your device" which sends them to onboarding. This is easy to implement but doesn't account for if they have not granted a permission or if they have denied it. Some components to handle permission checking and a component to show would be a welcome PR at some point.

@kevin-birdy you are welcome to weigh in here if you like.

**Comment by kevin-birdy** [comment]
FWIW I've always been 100% behind that line of thinking @burkeshartsis — it's a bit more of a longterm goal, but I would definitely vote to attack the problem via well-timed prompts within the actual experience of the app than go overkill in this onboarding PR.

**Pull request closed without merging**
