### PR TITLE
feat: Follower request push notification opens to connect tab

### PR DESCRIPTION
**Pull request by vinnyjth**
## DESCRIPTION

29E31F61-F7BA-491A-9161-170920494E79_1_105_c

### What does this PR do, or why is it needed?

We need to open up to the connect tab since iOS user's don't get the cool button.

### CODE REVIEW

**Comment by redreceipt** [comment]
was that supposed to be a GIF? I was gonna forego trying to test if I can see what it looks like

**Comment by vinnyjth** [comment]
> was that supposed to be a GIF? I was gonna forego trying to test if I can see what it looks like

yah it was, try this

https://user-images.githubusercontent.com/1637694/113584431-e0bf6600-95f8-11eb-9ef3-0e68f680cea5.mov

**Comment by vinnyjth** [comment]
https://user-images.githubusercontent.com/1637694/113584564-0c425080-95f9-11eb-8ca0-166d9d168b18.mov

**Comment by redreceipt** [comment]
niiiiiice

**Review by redreceipt — APPROVED** [review]

**Pull request merged**
