### PR TITLE
fix: replace graphql-tag with @apollo/client > gql

### PR DESCRIPTION
**Pull request by nlewis84**
closes https://github.com/ApollosProject/apollos-apps/issues/1901

### CODE REVIEW

**Comment by nlewis84** [comment]
ran `yarn && yarn storybook` and app fired up with no errors.

**Comment by redreceipt** [comment]
This is awesome. Go ahead and remove all the references from the package JSON files too and rerun yarn so it's completely gone from the repo.

**Comment by nlewis84** [comment]
This should be a chore: and not a fix:, huh?

**Comment by redreceipt** [comment]
I'd probably have done it as a "chore" but doesn't really matter. fixes show up in the changelog, chores don't. that's the difference. Also looks like you still have some tests failing.

**Comment by nlewis84** [comment]
I'm not seeing what the problem is. It is with a file that doesn't interact with the gql changes. ui-kit>Card>CardWrapper. The test fail message isn't helping me much.

**Comment by redreceipt** [comment]
Run `yarn test` locally inside the packages until you find the culprit. Try ui kit and ui connected first. But this is a big PR so it could be hiding anywhere. Unfortunately the CI isn't really helpful in finding the failure sometimes.

**Comment by nlewis84** [comment]
Any idea how to change that test in `PrayerExperienceConnected.tests.js`? This passes the test, but I don't think that it should reference graphql-tag and still pass.

**Comment by redreceipt** [comment]
Yea we shouldn't reference graphql tag anywhere. Not sure why we're mocking it out there. Try just importing gql in that file like normal from Apollo client

**Comment by nlewis84** [comment]
I had to import gql with an alias prepended with `mock`, but that seemed to get it working. Jest did not want me to use out-of-scope variables.

**Comment by redreceipt** [comment]
Weird! Why was gql out of scope there?

**Comment by nlewis84** [comment]
I don't know, but that is probably why we were assigning `const gql = jest.requireActual('@apollo/client');` within the mock function.

**Comment by redreceipt** [comment]
this would probably work

`const { gql } = jest.requireActual('@apollo/client');`

**Comment by nlewis84** [comment]
I think that tried `const gql = jest.requireActual('@apollo/client');` and it didn't work. I'll try it your way. Would that be preferred to the mockGql alias?

**Comment by redreceipt** [comment]
yea that way won't work, it's not the default export of `@apollo/client`

**Comment by redreceipt** [comment]
yea I'd say leave it like it was if possible to avoid any other side effects. the preferred way is to understand why it needs to be mocked in the first place and fix that ;)

**Comment by nlewis84** [comment]
That makes sense! This worked.

**Review by redreceipt — APPROVED** [review]
nice work!

**Pull request merged**
